### ISSUE TITLE
Include tests & doc in pypi release

### ISSUE THREAD

**Issue by ceball** [holoviz/param#103]
Currently they're not included

**Comment by ceball** [comment]
Do this if it makes sense, or delete the issue.

**Comment by ceball** [comment]
#219 would cover tests

**Comment by jlstevens** [comment]
I've not seen any open source project include their docs within the package for many years now. @tonyfast also points out that the conda-forge feedstock is running the tests for param and numbergen.

On this basis, I am inclined to close this issue. Feel free to comment and reopen it if you have any objections.
