### ISSUE TITLE
ObjectSelectors should list the allowed objects in the exception

### ISSUE THREAD

**Issue by jlstevens** [holoviz/param#118]
Line [953 of __init__.py](https://github.com/ioam/param/blob/master/param/__init__.py#L953-L965) generates an exception that isn't very helpful.

Any reason this exception can't be returned instead?

``` python
raise ValueError("%s not in Parameter %s's list of possible objects: %r" \
                             %(val,attrib_name, self.objects))
```

**Comment by jbednar** [comment]
I.e., you want to add self.objects to what's printed?  That seems reasonable, though I don't know if the list of objects will always be something that can be printed in some reasonable format.  I *think* it would be ok...

**Comment by jlstevens** [comment]
That is correct:  this is something Bas commented on in Gitter (he encountered the exception when using HoloViews). I generally think listing the allowed objects would be helpful...

**Comment by philippjfr** [comment]
The error now includes the valid objects, e.g.:

> ValueError: D not in Parameter b's list of possible objects, valid options include [A, B, C]
