### ISSUE TITLE
Python3 parameter defaults bug

### ISSUE THREAD

**Issue by philippjfr** [holoviz/param#148]
In holoviews we encountered a recurring bug where an existing parameter would not appear in Parameterized.defaults() sporadically. The original issue can be found here: https://github.com/ioam/holoviews/issues/1005

**Comment by jbednar** [comment]
From the hv issue, it sounds like it could be difficult to make a test script that would reproduce this problem?

**Comment by jbednar** [comment]
Assigning to Philipp to come up with a reproducer or to close it if it cannot be reproduced.

**Comment by philippjfr** [comment]
Definitely appears broken, and not intermittently:

```python
import param

class Test(param.Parameterized):
    
    lod = param.Dict(default={'factor': 10, 'interval': 300,
                              'threshold': 2000, 'timeout': 500})
    
t = Test()
t.param.defaults()
```
