### ISSUE TITLE
Move remaining param documentation out of topographica

### ISSUE THREAD

**Issue by ceball** [holoviz/param#157]
Should go through all param docs in Topographica (maybe it's just http://ioam.github.io/topographica/User_Manual/parameters.html now) and see what's worth keeping in Topographica (we'll likely want at least some parameter documentation for topographica users), and what's worth moving to param (or deleting).

**Comment by jbednar** [comment]
Sure, seems like there might be a little worth stealing from there, though there isn't much to it...

**Comment by ceball** [comment]
See #313
