### ISSUE TITLE
Clean up serialization

### ISSUE THREAD

**Issue by ceball** [holoviz/param#158]
I have added some notes about our existing serialization protocols at https://github.com/ioam/param/wiki/Serialization. 

We still need to note shortcomings (e.g. things that are problematic to serialize), and I think we should clean up the existing serialization a bit. E.g. while there could be stuff for serializing an object that's common between pickle and script_repr we don't provide any standard way to do that.

**Comment by ceball** [comment]
Note: see https://github.com/ioam/param/issues/166#issuecomment-325225105

**Comment by jbednar** [comment]
There's been progress on serialization, and remaining work is covered in other open issues and PRs.
