### ISSUE TITLE
ObjectSelector: pick first of objects if no default supplied?

### ISSUE THREAD

**Issue by ceball** [holoviz/param#164]
For an ObjectSelector with default of None and some objects in its list, seems like it would make sense to set its value to the first from the list

Then, instead of:
```
dates = [StartEndDates(),Duration()]

class SomeFn(param.ParameterizedFunction):
    date_range = param.ObjectSelector(default=dates[0],objects=dates)
    def __call__(self,**params):
        p = param.ParamOverrides(self,params)
        print(p.date_range.get())
```

I could do this:
```
class SomeFn(param.ParameterizedFunction):
    date_range = param.ObjectSelector(objects=[StartEndDates(),Duration()])
    def __call__(self,**params):
        p = param.ParamOverrides(self,params)
        print(p.date_range.get())
```

Should think carefully about it, but maybe add a ``default_to_first``-like argument to ObjectSelector. But ``default_to_first`` would need to default to False to avoid changing behavior for existing code that uses ObjectSelector with a default of None but a non-empty list of objects (something to consider for a new release).

**Comment by ceball** [comment]
Will be able to remove code from paramnb (https://github.com/ioam/paramnb/commit/df12e4b37e040963086cbf12c885a909af2b412c) when this is implemented.

**Comment by jbednar** [comment]
We added `Selector` with this semantics, and for this reason it's preferred over `ObjectSelector`, but we kept `ObjectSelector`'s semantics the way it was for backwards compatibility.
