### ISSUE TITLE
Rename Date and DateRange params to DateTime and DateTimeRange?

### ISSUE THREAD

**Issue by ceball** [holoviz/param#169]
Or at least clearly document that they expect datetimes.

**Comment by randomstuff** [comment]
Yes, using `Date` for `datetime` is weird. It'd be nice to have use `DateTime` for `datetime` dans `Date` for `date`.

**Comment by jbednar** [comment]
Closing in favor of https://github.com/holoviz/param/issues/346, which links to a PR adding CalendarDate to distinguish dates from datetimes.
