### ISSUE TITLE
Stop setting class attributes during initialization

### ISSUE THREAD

**Issue by ceball** [holoviz/param#174]
```
>>> import param
>>> class X(param.Parameterized):
...     y = 1
...     z = param.Parameter(10)
... 
>>> x = X(y=9)
WARNING:root:X00003: Setting non-parameter attribute y=9 using a mechanism intended only for parameters
```

**Comment by jlstevens** [comment]
I would not want to set class attributes this way and I would rather have an error than the current behavior (I want to handle setting class attributes myself!).

**Comment by ceball** [comment]
I thought this was the warning you were complaining about? If not this one, then which one did you mean? If it is this one, but you're getting it in some other way, could you give me an example? I'm a bit confused.

I created this issue not because I think we should allow what I described in my opening comment, but to record whatever decision we make...so that when you complain about param warnings again in the future, I can refer you back to it ;) But that will only work if we're discussing the right situation in which you get the warning!

**Comment by jlstevens** [comment]
The problem is that param is assuming it has anything to do with class attributes. I don't want param to have any say about class attributes that aren't parameters and I certainly don't want it to set them!

I think the warning behavior should be optional and off by default.

**Comment by jlstevens** [comment]
To be clear, I would prefer an exception if I misspell a parameter name along the lines of 'Cannot set parameter 'fooz' as no such parameter exists'.

A fancier implementation could say something like:

"Cannot set parameter 'fooz' as no such parameter exists. Similar parameters: 'foo','foz'"

**Comment by ceball** [comment]
Ok, I think I get you now, but let's check! You want this:

```
>>> import param
>>> class X(param.Parameterized):
...     y = 1
...     z = param.Parameter(10)
... 
>>> x = X(y=9)
Error: X has no parameter 'y' 
>>> X.y = 9
>>> X.y
9
```

Whereas you currently get a warning in both cases (``X(y=9)`` and ``X.y=9``).

Have I described what you want?

**Comment by jlstevens** [comment]
> Have I described what you want?

Yes, I think so! Though @jbednar and @philippjfr may also want to chime in...

**Comment by philippjfr** [comment]
Yes I think that's more sensible.

**Comment by ceball** [comment]
> Though @jbednar and @philippjfr may also want to chime in...

Just because I finally described what you want doesn't mean I agree with it, nor does it imply anything about whether or not I would implement it even if did I agree with it ;)

**Comment by jbednar** [comment]
I do agree with X.y=9 working, at least for an existing class parameter (one defined in the class definition).  The purpose of this warning is to catch typos and references to no-longer-existing parameters, neither of which applies when the class parameter is explicitly defined.

**Comment by philippjfr** [comment]
Right, and I think an exception in the constructor is more consistent because you should be catching attributes explicitly. If you want the constructor to continue warning instead of throwing an exception I have no strong objection but imo it definitely shouldn't be setting non-parameters.

**Comment by ea42gh** [comment]
I'd suggest wording the error message
`Error: X has no parameter 'y' ` in the last code snippet starting with
`Ok, I think I get you now, but let's check`
 a bit differently:

when I first read it, my reaction was 'Huh? The class DOES have a class parameter y???',
i.e., the differentiation between `parameters` and `class parameters` may not be obvious to
a user such as me...

**Comment by jbednar** [comment]
The distinction here is between a class *attribute* and a class *parameter*.  Maybe we could capitalize the P in 'parameter' to indicate that this message is simply saying that even though there is an attribute 'y', it's not a Parameter, and thus it is not meant to be set using a mechanism created for setting Parameters.

If y is not a Parameter, I vote for making `X(y=9)` for y not a Parameter be an exception; I really can't see why it would ever be valid to do.  And then the exception message could be "Error: X has no Parameter 'y'; cannot set 'y' in the constructor".

**Comment by jlstevens** [comment]
That is a much better message and the behavior I was looking for.

**Comment by ea42gh** [comment]
class attribute vs class parameter:
might you include both terms in the message to alert a user
with middling python skills (such as mine!) what they need to think about?

The distinction attribute/parameter requires a user to have a good grasp of python technical terms...

**Comment by jbednar** [comment]
Maybe 'Error: param.Parameterized object `X` has no Parameter 'y'; cannot set 'y' in the constructor".

**Comment by ea42gh** [comment]
That would have me scratch my head too!
How about referring to   paramnb in the message?

**Comment by jbednar** [comment]
The message doesn't come from paramnb, it comes from Param.

**Comment by maximlt** [comment]
Trying to summarize the current behavior and the output of the discussion above.

![image](https://user-images.githubusercontent.com/35924738/229812048-2dba177d-54ea-4dd8-8090-3294084564c0.png)

[It was suggested](https://github.com/holoviz/param/issues/174#issuecomment-394470555) that `P(x=...)` should raise an Exception when `x` is not a Parameter, with the following error message: `"Error: P has no Parameter 'x'; cannot set 'x' in the constructor".`.  This could be improved by suggesting Parameter names, as [suggested here](https://github.com/holoviz/param/issues/174#issuecomment-315632561).

[It was also suggested](https://github.com/holoviz/param/issues/174#issuecomment-315984988) that `P.x = ...` should not emit a warning, at least when `x` is already a class attribute. It [was also suggested](https://github.com/holoviz/param/issues/174#issuecomment-315632166) that Param should have nothing to do or say about regular class attributes.

Given that, I'd say that wrt the screenshot above:
- the first two warnings should be removed
- the last two warnings should be turned into an exception with the suggested message, optionally with a suggestion of alternative Parameter names to use in the constructor.
