### ISSUE TITLE
Consider using functools.singledispatch to replace 'registries of functions to call depending on type'

### ISSUE THREAD

**Issue by ceball** [holoviz/param#177]
https://docs.python.org/3/library/functools.html#functools.singledispatch

E.g. could be used to replace script_repr_reg.

There's a backport to python 2, but it has to be installed from pypi. So this is something to consider in the distant future.

**Comment by jlstevens** [comment]
> So this is something to consider in the distant future.

2020 when Python 2 is no longer supported?

**Comment by ceball** [comment]
Just a note that I vaguely recall we often don't respect the class hierarchy when looking things up in dicts, but various times we should.

**Comment by tonyfast** [comment]
@jbednar doesn't likely to be urgent for anyone anytime soon.

**Comment by ceball** [comment]
> Just a note that I vaguely recall we often don't respect the class hierarchy when looking things up in dicts, but various times we should.

E.g.

https://github.com/holoviz/param/blob/master/param/parameterized.py#L2324

vs

> Where there is no registered implementation for a specific type, its method resolution order is used to find a more generic implementation.

(https://docs.python.org/3/library/functools.html#functools.singledispatch)
