### ISSUE TITLE
Plan for validating inputs and outputs

### ISSUE THREAD

**Issue by jlstevens** [holoviz/param#196]
After many conversations with @jbednar , @philippjfr  and @ceball, I'll try to summarize the core ideas we have for taking validation (especially output validation) forwards:

* A concept of a 'validator' which is simply a callable that takes a value and either does nothing (returns None) or raises an exception, complaining about that value. Here is the simple type checking validator we are using implicitly:

```python
def typechecker(cls): # Builds a validator
   def typecheck(val):
   if not isinstance(val, cls):
       raise TypeError('Value {val} is not a {cls}'.format(val=str(val), cls=str(cls))
   return typecheck
```

One wrinkle is that we need to decide whether we want to support parameter *classes* as validators (e.g ``param.Number``)  or just instances (e.g ``param.Number(bounds=(0,None))``). 

We also need to decide whether we want to allow simple builtin types to do isinstance checks e.g ``str, int, float, dict, list, tuple`` etc. The reason to do this is that this could be much more succinct for lots of common cases.

* Parameters can be *made* into validators by consolidating the ``check_val`` methods into ``__call__`` so that ``param.Integer(bounds=(0,None))(3)`` works (this will return ``None`` but ``-10`` would complain.

* To validate the return values of methods, we propose some sort of decorator:

```python
   @param.validate(validator)
   def foo(*args,*kwargs):
      ...
      return bar
```

All this decorator does is pass the return value (``bar``) to the ``validator`` and *then* tries to return ``bar``. The validator then has the opportunity to complain about ``bar``.

**Note:** This decorator assumes you can express what you want with a single validator but we want a separate, more general decorator for now:

```python
param.validation(validator1, validator2, ...)
```

In terms of our dashboarding discussion, the idea of ``param.viewable`` would just be an alias for ``param.validator(param.Viewable)`` where ``param.Viewable`` is a simple subclass of ``param.Parameter`` (for now).

**Why introduce validators?**

Parameters are fantastic validators for simple literals like ints, strings, floats etc and as mentioned above can easily fit into the validator concept. The issue is that parameters do not currently allow nested declaration for composite types beyond one level (e.g specifying that a list must contain tuples of ints etc).

**Future directions**

* It *might* be possible to enable param to support composite types by generalizing what ``class_`` allows so that ``class_`` itself can accept parameters (that in turn can have ``class_`` set as another parameter etc).

* Another idea is that param could allow building of custom/composite parameters out of pieces that do bits of validation. Something like `` foo = param.TypeCheck(int) | param.BoundsCheck(0,None)`` for something that ensure the value is an int greater than zero. Obviously this example is redundant with ``param.Integer`` but you can imagine building far more sophisticated, custom checks.

* Param itself could be refactored to use validators internally instead of ad hoc tests and exceptions.

* In HoloViews, it would be nice to have a system to specify nested structures (e.g a holomap or overlays, each of which is an image with one or more curves on top) that are also validators. In other words, you can call this composite object with either another type specification or a concrete HoloViews object to validate it. In HoloViews, this would be nice to help separate notebook testing into type checks, parameters check and data checks.

* Although we would like to specify holoviews composite types, in principle it would be great to generalize this idea in param so anyone can specify types for nested/composite objects.

On a personal note, I *like* Python being a dynamic language and I would hate to see type specifications appear everywhere in situations where they don't add sufficient value! The reason I like this suggestion is there a few specific places (e.g holoviews operations) where type specifications would be helpful.

We should probably link in some of the relevant issues (feel free to edit this comment). Hope that makes sense!

**Comment by jbednar** [comment]
Thanks; that's very helpful!

> One wrinkle is that we need to decide whether we want to support parameter *classes* as validators (e.g ``param.Number``)  or just instances (e.g ``param.Number(bounds=(0,None))``).

I guess we could allow either one, though the checks will be more stringent with the additional info provided in an instance.

> We also need to decide whether we want to allow simple builtin types to do isinstance checks e.g ``str, int, float, dict, list, tuple`` etc. The reason to do this is that this could be much more succinct for lots of common cases.

I'm not sure how those would be more succinct; don't we already have corresponding Parameters for all those cases?  param.Integer doesn't seem particularly less succinct than "int" (all on one line in either case), and gives the ability to specify bounds.

> * To validate the return values of methods, we propose some sort of decorator:
> 
> ```python
>    @param.validate(validator)
>       def foo(*args,*kwargs):
>             ...
>                   return bar
>                   ```
> 
> All this decorator does is pass the return value (``bar``) to the ``validator`` and *then* tries to return ``bar``. The validator then has the opportunity to complain about ``bar``.

"validate" doesn't seem to cover the intended usage of this code; shouldn't that be something like ``param.returns(param.Integer(bounds=0,10))`?

> **Note:** This decorator assumes you can express what you want with a single validator but we want a separate, more general decorator for now:
> 
> ```python
> param.validation(validator1, validator2, ...)
> ```

I'm not sure what this is for.

> In terms of our dashboarding discussion, the idea of ``param.viewable`` would just be an alias for ``param.validator(param.Viewable)`` where ``param.Viewable`` is a simple subclass of ``param.Parameter`` (for now).

I don't think we'd want such an alias; why wouldn't we use the general form ``param.returns(param.Viewable)``?

**Comment by jlstevens** [comment]
> I guess we could allow either one, though the checks will be more stringent with the additional info provided in an instance.

Agreed.

> ... param.Integer doesn't seem particularly less succinct than "int"

The latter is 4.33x shorter than the former even if it is all on one line. I don't mind only supporting parameters classes/instances for now but I think simple types could be a nice, more readable shortcut.

> "validate" doesn't seem to cover the intended usage of this code; shouldn't that be something like param.returns.

Here ``param.validate`` and ``param.returns`` are the same idea, I just wasn't quite sure of a name yet.

> ... shouldn't that be something like ``param.returns(param.Integer(bounds=0,10))``?

Yes, where ``param.Integer(bounds=0,10))`` is an example of a ``validator``. I think we both mean the same thing, I just tried to express the idea in general while you gave a concrete example of it.

> I'm not sure what this is for.

It is because it might be nicer to specify a list of conditions (validators) instead of always having to fold all the conditions into a single one. The single validator approach is the long-term goal but supporting a list like this might be an easier way to express complex requirements in the short term. Anyway, this isn't an either/or situation, just a suggestion for what might be a useful alternative for now.

> I don't think we'd want such an alias; why wouldn't we use the general form param.returns(param.Viewable)?

Again, this is just confusion about the name of the same decorator. If you agree ``param.returns`` accepts a validator (i.e some condition that must be satisfied by the return value), I'm happy to settle on that.

**Comment by jbednar** [comment]
Sounds good.

**Comment by tonyfast** [comment]
@jlstevens can you look at this and see if there is anything remaining to do? If not, let's close it!

**Comment by jlstevens** [comment]
@tonyfast I don't think this issue has been tackled at all. As far as I know, we have no mechanism at all for validating outputs right now so I think this issue stays open.

**Comment by jlstevens** [comment]
Looks like I was wrong, since #312 multiple outputs can be named and typed which satisfies what I had in mind when I opened this issue. Closing.
