### ISSUE TITLE
pprint does not handle circular references

### ISSUE THREAD

**Issue by philippjfr** [holoviz/param#209]
When there are circular references on a Parameterized object the pretty printing causes a recursion error:

```python
class A(param.Parameterized):
    
    b = param.Parameter()
    
class B(param.Parameterized):
    
    a = param.Parameter()
    
a = A()
b = B(a=a)
a.b = b
a.pprint()
```

I'd suggest there should be a maximum depth for the pretty printer, anything more than 1 or two levels deep will become unreadable anyway.

**Comment by jbednar** [comment]
Fixed in #499.
