### ISSUE TITLE
Warning message 'Setting non-parameter attribute' could be improved?

### ISSUE THREAD

**Issue by ea42gh** [holoviz/param#228]
The warning
`Setting non-parameter attribute html=[] using a mechanism` took me quite a while to parse
when I first encountered it.

Could this be improved? It gets triggered by an invalid argument
setting that is a likely bug in the user code.
Ideally I'd like to see something like  'invalid argument html=[] in xxxx call'
that points me to the xxxx fn with the offending argument.

**Comment by ceball** [comment]
You're right, it could be improved. Thanks for the feedback.

We have an issue about stopping param from setting non-parameter class attributes, but haven't implemented the proposal yet. The wording and/or information reported will be improved at the same time.

The proposal is briefly outlined in https://github.com/ioam/param/issues/174#issuecomment-315636661 (although that's just about the mechanism; the exact wording and information reported in messages hasn't yet been decided).

**Comment by tonyfast** [comment]
superceded #174
