### ISSUE TITLE
Switch to unittest2 on older pythons

### ISSUE THREAD

**Issue by ceball** [holoviz/param#246]
In tests/__init__.py, we have some redundant code to use unittest2 on python < 2.7:

```
if sys.version_info[0]==2 and sys.version_info[1]<7:
    del sys.modules['unittest']
    sys.modules['unittest'] = __import__('unittest2')
```

(redundant since we dropped 2.6 and earlier)

I plan to change that (and add conditional dependency to list of test dependencies) so we use unittest2 for whichever versions of python we support that don't use the current python 3 unittest. 

(One small example: assertRegexp type names are deprecated in py3 unittest - they're assertRegex now.)

**Comment by tonyfast** [comment]
closing. seems to be covered by  #423
