### ISSUE TITLE
Cleanup and decisions required for "depends"/watching before release

### ISSUE THREAD

**Issue by ceball** [holoviz/param#262]
(WIP, just notes right now, but please feel free to add stuff and/or edit. I'll be closing various related issues and moving anything still relevant here too. "proposals" are just something to start from. maybe some of these should be expanded to become separate issues so they can be discussed more easily? maybe we should meet?)

# Decisions

* [x] what to call 'subscribing'/'watching'? proposal: 'watching'
* [x] what to call `@depends`? proposal: `@depends` (it can expand or restrict the default dependencies)
* [x] what are default dependencies of a method? proposal: all parameter values of the object.
* [ ] what can be depended on? proposal: 
  * parameter values and metadata (aka parameter attributes, e.g. "constant") for parameters of the object itself 
  * parameters of subobjects (?parameters of any subobject, or only ones that are themselves values of a parameter?)
  * default is to depend on all parameter values of object
  * can depend on all parameters of a subobject via "subobject.param"
* [ ] ways to watch. proposal: via `@depends(..., watch=True)`, and by calling `object.param.watch()` 
* [ ] ways to specify things to depend on/watch. proposal: (1) via strings (e.g. `@depends("parameter")`,`@depends("subobject.parameter")`, `@depends("parameter:constant")`, `@depends("subobject.param")`, `object.watch(fn, "parameter")`, `object.watch(fn, "subobject.parameter")`, `object.watch(fn, "parameter:constant")`. And also (2) explicitly where possible (e.g. `object.watch(fn, parameter="x", attribute="constant")` though not necessarily those terms.
* [x] terminology: e.g. a `Change` is currently a namedtuple `("what attribute obj cls old new")` where `what` is parameter value or metadata such as `constant`, `attribute` is the name an object has for the parameter, `obj` is instance. But then we have `watch(parameter_name, parameter_attribute=None)` with `None` meaning the value i.e. `what` in a `Change`. So confusing :) We probably need to make various things in param consistent, unrelated to this work.
* [ ] There is a continuum of possibilities for what the watch mechanism supplies as arguments. The simplest option is to call the callback with the new parameter value, the most sophisticated option is to offer very rich Change objects. There are tradeoffs to be made here in terms of flexibility/ease of use and offering different 'modes' would also involve tradeoffs. I don't feel any one choice is clearly optimal. 
* [ ] (todo: batch, [some notes below](https://github.com/ioam/param/issues/262#issuecomment-421147360) plus see #259, #263 )
* [ ] (todo: class vs instance)
* [ ] notebook documentation
* [ ] docstrings
* [ ] unit tests

(Note: comments on code have generally been going into #253)

# Internal cleanup required

* 

# Possible future work 

For which we should create new issues

* [ ] cache/memoize (expand/replace what was in #250)
*

**Comment by jlstevens** [comment]
I'm happy with the terminology of `watching`. My only objection to the terminology of 'subscribers' is that we use it in holoviews too for something a bit different.

**Comment by jlstevens** [comment]
To add one point I would like addressed:

* In `Change` objects, `attribute` should be called `parameter` (we've discussed this already).

I understand the value of `Change` named tuples in some circumstances but they seem a bit unwieldy to me for simple tasks/callbacks. I'm not suggesting we get rid of them (or even offer a different 'modes' for invoking callbacks) as consistency is valuable. That said, it is worth enumerating and thinking about this set of related API questions:

* Do we support positional arguments or kwargs in callbacks? Or both? Currently the mechanism merged to master assumes a single positional argument but we will want batched watching of parameters (#259) which means callbacks will need to accept multiple arguments somehow.
* Does setting parameters with something like `foo.x = 3` 'partially' trigger batched callbacks involving `x`? Or do batched callbacks only trigger when all required parameters are set via `set_param` only? This would mean there are two classes of callback (batched and unbatched) that don't quite mix. To partially trigger a callback, you would need to use kwargs to supply default values.

* There is a continuum of possibilities for what the watch mechanism supplies as arguments. The simplest option is to call the callback with the new parameter value, the most sophisticated option is to offer very rich `Change` objects. There are tradeoffs to be made here in terms of flexibility/ease of use and offering different 'modes' would also involve tradeoffs. I don't feel any one choice is clearly optimal.

I'm just listing things to think about and have no strong opinion other than I *think* batched watching should only trigger when the full set of specified parameters are changed via `set_param`.

**Comment by jbednar** [comment]
> Or do batched callbacks only trigger when all required parameters are set via set_param only? This would mean there are two classes of callback (batched and unbatched) that don't quite mix. To partially trigger a callback, you would need to use kwargs to supply default values.

I may be misunderstanding this a bit, but defining batched and non-batched callbacks separately doesn't sound feasible to me.  The *same* system should be able to update when one does "obj.x=2" as when one sets a bunch of obj's parameters at once; surely we can't require users to set up in advance every combination of batched or non-batched callbacks they might need?

**Comment by jlstevens** [comment]
What you declare is the *maximal* set of parameter the callback cares about. Then the *maximal* batching is when all those parameters are changed at once. The watch mechanism then batches as much as it can for whatever applicable subset of parameters are updated.

**Comment by jbednar** [comment]
Sounds good, thanks.

**Comment by jlstevens** [comment]
I've ticked off the bullet point about the terminology around the `Changed` named tuple as recent PRs have helped clean that up.

**Comment by jbednar** [comment]
Closing as the code is already merged and released, while the documentation is covered by #313.
