### ISSUE TITLE
Delete 'root' from Param logging messages?

### ISSUE THREAD

**Issue by jbednar** [holoviz/param#267]
From @sdrobert: 

> Parameterized(name="param_union").warning("overwriting parameter %s",k)

Is there any way to avoid the 'root' part of the message?

WARNING:root:param_union: overwriting parameter a
WARNING:root:param_union: overwriting parameter b

From @ceball:

I don't know what purpose 'root' serves in general.

param's logging system uses Python's logging module (see https://github.com/ioam/param/blob/master/param/parameterized.py#L32); I think everyone would be happy to see it simplified and/or clarified, but nobody's had time to work on it. This link indicates the name's from the logging module's "root" logger; setting param.logger to some other named logger would probably change "root" to that name (because param would be using a different logger).

From @jbednar:

Maybe we should just declare that the root logger has the name "param", to give people an idea where these messages come from?

**Comment by sdrobert** [comment]
My two cents (if desired):

From the Python docs:

```
The name is potentially a period-separated hierarchical value, like foo.bar.baz (though it could also be
just plain foo, for example). Loggers that are further down in the hierarchical list are children of loggers
higher up in the list. For example, given a logger with a name of foo, loggers with names of foo.bar,
foo.bar.baz, and foo.bam are all descendants of foo. The logger name hierarchy is analogous to the
Python package hierarchy, and identical to it if you organise your loggers on a per-module basis using
the recommended construction logging.getLogger(__name__). That’s because in a module, __name__ is
the module’s name in the Python package namespace.
```

Staying faithful to the `logging` system seems most sensible to me. For functions like `param_union`, you'd use the logger ``"param"``, corresponding to the package's logger. Then if you want to submit a warning through a parameterized instance, you'd ask for the logger ``"param".<name of parameterized instance>``, which would inherit from the ``"param"`` logger and any handlers/formatters. Here's an example:
``` python
import logging
param_logger = logging.getLogger('param')
formatter = logging.Formatter(fmt='%(levelname)s:%(name)s: %(message)s')
handler = logging.StreamHandler()
handler.setFormatter(formatter)
param_logger.addHandler(handler)
param_logger.warning('foo')  # prints "WARNING:param: foo"
param_bar_logger = logging.getLogger('param.bar')
param_bar_logger.warning('foo')  # prints "WARNING:param.bar: foo"
```

An additional plus to this method is that you're no longer mucking with the root logger. Messing with the root logger introduces all sorts of weirdness into other `logging`-based code, as any new loggers inherit from the root.

I'd be happy to help with this one, but I'd like to know what sort of expectations there are for the style of logging message before I go hacking away.

Best,
Sean

**Comment by jbednar** [comment]
That all sounds good to me, thanks!  I don't know of anything that is relying on the details of the logging message format, and in any case we are gearing up for a Param 2.0 release relatively soon where we can have API-breaking changes anyway.

**Comment by jbednar** [comment]
(Note that Param's logging support *long* predates the logging module, so it shouldn't be surprising that it wasn't fully adapted to conform to how the logging module works.  Its logging actually predates most of the rest of Python too, I think, as I believe we copied it from some 1995-era C code of mine...)

**Comment by maximlt** [comment]
I believe this was done in https://github.com/holoviz/param/pull/330:

```python
import param

param.Parameterized(name="param_union").param.warning("overwriting parameter %s", 1)
```

Output:
```
WARNING:param.param_union: overwriting parameter 1
```

Closing then.
