### ISSUE TITLE
Rename Parameter subclasses' "**params" arguments

### ISSUE THREAD

**Issue by sf-issues** [holoviz/param#27]
Converted from SourceForge issue 2513082, submitted by ceball
Submit Date: 2009-01-16 12:02 GMT

E.g.

class Dynamic(Parameter)
   def __init__(self,**params):
        super(Dynamic,self).__init__(**params)

The name of **params is confusing here. It should be **kw - or in fact anything except **params, which is a name we use specifically for passing parameter values to methods of Parameterized instances.

**Comment by kcpevey** [comment]
@jbednar and I agree that this convention can be confusing but its been in place for many years and it's probably more confusing to change it now.
