### ISSUE TITLE
Parameterized.__deepcopy__

### ISSUE THREAD

**Issue by sf-issues** [holoviz/param#28]
Converted from SourceForge issue 2888867, submitted by ceball
Submit Date: 2009-10-29 15:52 GMT

Slow opening of cfs, etc. deepcopy slot. 

(https://mail.google.com/mail/?shva=1#search/%22Topographica-cvs+Digest%2C+Vol+30%2C+Issue+19%22/11dcade03c31c7ca)

**Comment by ceball** [comment]
I don't know what this is referring to :)

Maybe allowing control over deepcopy via a deepcopy slot? Which might be related to the value of instantiate by default?

**Comment by kcpevey** [comment]
Closing as it is no longer clear what it's referring to
