### ISSUE TITLE
Color does not respect allow_None

### ISSUE THREAD

**Issue by sdrobert** [holoviz/param#303]
Color throws away the keyword ``allow_None``. See https://github.com/ioam/param/blob/c17db9bc02f35d55dc85f58d09b7ea5ab03c4171/param/__init__.py#L1714

**Comment by tonyfast** [comment]
This looks a small oversight. There are 2 easy ways to fix this. 

https://github.com/holoviz/param/blob/c17db9bc02f35d55dc85f58d09b7ea5ab03c4171/param/__init__.py#L1721
