### ISSUE TITLE
Keep `names` attribute and `objects` attribute of an `ObjectSelector` in sync

### ISSUE THREAD

**Issue by sdc50** [holoviz/param#309]
Now that the `ObjectSelector` accepts a mapping as the `objects` argument of the constructor it would be nice to also allow the `objects` attribute of the class to be set with a mapping. Otherwise, if the `objects` attribute is changed after instantiation then the `names` attribute is out of sync. For example:

![image](https://user-images.githubusercontent.com/6454472/50022610-59223900-ffa2-11e8-937e-c777d3d28e8b.png)

One suggestion would be to make `objects` a property that has a setter:
```python
class ObjectSelector(Selector):
...
     __slots__ = ['_objects','compute_default_fn','check_on_set','names']

    @property
    def objects(self):
        return self._objects

    @objects.setter
    def objects(self, objects):
        if objects is None:
            objects = []
        if isinstance(objects, collections.Mapping):
            self.names = objects
            self._objects = list(objects.values())
        else:
            self.names = None
            self._objects = objects

    # ObjectSelector is usually used to allow selection from a list of
    # existing objects, therefore instantiate is False by default.
    def __init__(self,default=None,objects=None,instantiate=False,
                 compute_default_fn=None,check_on_set=None,allow_None=None,**params):
        self.objects = objects
        ...
```

Then the behavior would be like I would expect:
![image](https://user-images.githubusercontent.com/6454472/50022669-92f33f80-ffa2-11e8-8346-0d0c06cb1647.png)

**Comment by philippjfr** [comment]
This should be fixed before we release 1.9.
