### ISSUE TITLE
Param documentation

### ISSUE THREAD

**Issue by jbednar** [holoviz/param#313]
Param's website param.pyviz.org is appalling.  It has a brief intro, but no real documentation, with no clue about any of the more powerful features of Param (certainly not any of the more recently added ones like depends, watch, and output) and outdated pointers to ParamNB and ParamTk and no mention of Panel.  Some previous issues mention bits of docs that do exist that need to be moved into the website (https://github.com/pyviz/param/issues/157, https://github.com/pyviz/param/issues/94), but really it needs some dedicated effort to provide actual, up to date content, because it's such a big part of how to use Panel.

**Comment by jbednar** [comment]
Just to start a grab bag of items that need documentation:

- Controlling order (definition order on py3.6+, sorted alphanumerically py2.7-3.5, within each precedence value; see https://github.com/pyviz/param/issues/185).

**Comment by cocoaaa** [comment]
Hi, having these items documented would be really helpful. Do you think the documentation will be updated in the near future? Or, are there places I can read more about them -- esp. item 3,4,5,6?

Thanks!

**Comment by ceball** [comment]
Extends #47 and #157 (have closed those).

**Comment by ceball** [comment]
@cocoaaa Bit late for your question, but I would look at panel's docs and examples for now (e.g. see panel.pyviz.org).

**Comment by kgullikson88** [comment]
@jbednar is there any documentation anywhere for some of those things? I am trying to figure out what `watch` does by turning it off and on, and can't tell. The controlling order thing is also something I've been trying to find and it sounds like it is possible.

**Comment by jbednar** [comment]
The docs at panel.pyviz.org are your best bet for now; search those for "param" and "watch" and you should see examples of watch in heavy usage. Watch doesn't need Panel, of course, but that's where it's currently documented. I apologize for that; my only defense is that no one has ever paid us to document Param, and we're paid to work on a whole lot of other things that don't leave any time to work on Param docs.  I can't even guess how long "document Param" has been `#`7 on my priority list, and only the first few ever get addressed. :-/

**Comment by kgullikson88** [comment]
No problem, I totally understand and appreciate the work you do!

**Comment by jbednar** [comment]
FYI: We now have paid-for time to develop proper Param documentation, so it will happen sometime in 2020!  Sooner rather than later, I hope, but we have a large set of tasks in the current plan of work, and this one isn't the first in the list.

**Comment by maximlt** [comment]
Param has now a proper documentation website, closing :)
