### ISSUE TITLE
Param error is incomplete and too ambiguous

### ISSUE THREAD

**Issue by sdc50** [holoviz/param#333]
When rendering a panel I get the following param error:

```
WARNING:param.: The Parameterized instance has instance parameters created using new-style param APIs, which are incompatible with .params. Use the new more explicit APIs on the .param accessor to query parameter instances.To query all parameter instances use .param.objects with the option to return either class or instance parameter objects. Alternatively use .param[name] indexing to access a specific parameter object by name.
```
![image](https://user-images.githubusercontent.com/6454472/57402712-806de280-719d-11e9-8620-9afbfbecde09.png)

As far as I can tell I am only using the new-style API. It would be helpful for debugging if the error message where a little more specific about where the incorrect usage came from, or at least what attribute was being accessed in the old way. 

(See attached files to reproduce)
[Archive.zip](https://github.com/pyviz/panel/files/3158988/Archive.zip)

**Comment by jbednar** [comment]
I can't find the text of that error message in the current codebase, nor anything like it, so I think the message has already been replaced or improved.
