### ISSUE TITLE
param.depends does not warn about unresolved parameters

### ISSUE THREAD

**Issue by philippjfr** [holoviz/param#357]
As the title says the depends decorator simply silently ignores attributes which are not parameters leading to unexpected behavior as in this example: https://stackoverflow.com/questions/58114082/why-is-my-plot-updated-by-panel-twice-when-i-change-a-button-setting-that-shou

We should make sure that it error or warns when a referenced parameter is not found.

**Comment by maximlt** [comment]
To be more explicit about this issue, in the example below we depend on `y` that doesn't exist and there's no warning/error that lets the user know they've done something wrong, either at the class or instance creating time

```python
import param

class A(param.Parameterized):
    x = param.Number(0)

    @param.depends('y')
    def debug(self): pass

a = A()
```
