### ISSUE TITLE
Checkbox Group in param?

### ISSUE THREAD

**Issue by wogandavid** [holoviz/param#377]
Are there any plans to include `Checkboxgroup` as a parameter? So far the only option (that I see) for selecting multiple options is `param.ListSelector`, but this shows up as a list, which is not as convenient as checkboxes.

https://panel.holoviz.org/user_guide/Param.html

**Comment by jbednar** [comment]
No current plans.  That would need not just a list of Booleans, but a list of Booleans with names, so I'm not sure how to define that as a meaningful Parameter.  param.ListOfNamedBooleans doesn't exactly roll off the tongue!  If you can think of a way to name and describe it in Param terms (i.e., not referring to any GUI elements, just the actual data involved) that makes sense, then it would be easy enough to add to Param (and then to Panel).

In the meantime, can you use something like this?

```
import panel as pn, param as pm
pn.extension()

class checks(pm.Parameterized):
    a = pm.Boolean()
    b = pm.Boolean()
    c = pm.Boolean(True)
    d = pm.Boolean()
    
class other(pm.Parameterized):
    i = pm.Integer(bounds=(0,5))
    c = pm.ObjectSelector(checks, precedence=-1, readonly=True)
    f = pm.Number(bounds=(-1,1))

o = other()
pn.Row(pn.panel(o.param, expand=True))
```
![image](https://user-images.githubusercontent.com/1695496/74344702-9f278800-4d72-11ea-8602-5abc2e80be57.png)

**Comment by philippjfr** [comment]
This is already possible using the ListSelector param. As @jbednar pointed out parameters should have meaning beyond GUI elements, if you need a specific visual representation Panel offers the ability to map to that representation:

```python
class Test(param.Parameterized):
    int_list                = param.ListSelector(default=[3, 5], objects=[1, 3, 5, 7, 9], precedence=0.5)

test = Test()
pn.Param(test, widgets={'int_list': pn.widgets.CheckBoxGroup})
```

<img width="54" alt="Screen Shot 2020-02-12 at 9 13 58 AM" src="https://user-images.githubusercontent.com/1550771/74348276-0d227e00-4d78-11ea-8334-f90a4b497280.png">

**Comment by wogandavid** [comment]
> This is already possible using the ListSelector param. As @jbednar pointed out parameters should have meaning beyond GUI elements, if you need a specific visual representation Panel offers the ability to map to that representation:
> 
> ```python
> class Test(param.Parameterized):
>     int_list                = param.ListSelector(default=[3, 5], objects=[1, 3, 5, 7, 9], precedence=0.5)
> 
> test = Test()
> pn.Param(test, widgets={'int_list': pn.widgets.CheckBoxGroup})
> ```
> 
> <img alt="Screen Shot 2020-02-12 at 9 13 58 AM" width="54" src="https://user-images.githubusercontent.com/1550771/74348276-0d227e00-4d78-11ea-8334-f90a4b497280.png">

Makes sense, the mapping worked. Very convenient. Initially it didn't occur to me that I could do that from reading the User Guide, but it is now. Thanks!

David
