### ISSUE TITLE
Literal serialization and deserialization

### ISSUE THREAD

**Issue by jlstevens** [holoviz/param#382]
The effort to serialize/deserialize parameterized objects is being restarted (see #159 and #153)  with the goal of controlling param state via REST APIs. As can be seen above, a lot of thought went into how much can be expressed in YAML in particular to support as much of param as possible.

The current focus on REST means that the immediate goal is to get JSON support working as that is the format most typically used for data exchange over the web. As JSON is less rich that YAML, I am now thinking about what can be achieved without using any YAML specific features. In particular, I am thinking about serializing the parameter values *only* (and not things like bounds, objects or other `Parameter` state).

Lastly note that this focus on JSON doesn't mean YAML can't be supported as long as only the subject of YAML is used that is supported by JSON.
I believe that a serialization approach based on what JSON can handle (i.e lists, mappings, numbers, strings, bools...) can still be very useful even if things like callables aren't supported. However, things like the `NumericTuple` parameter is very common in param code but tuples are not supported by JSON. Accepting this limitation would be very annoying so I propose that we serialize into what JSON supports (e.g a tuple would serialize into a JSON list) and deserialize by noting that a list can be easily cast into the tuple that the parameter requires. Here is how I think we can handle most parameters with JSON:

**Dynamic** Dynamic parameters have a current state that can often be serialized but also a callable that generates that state that can't be. Only the current state will be serialized.

**Number** Not a problem to accept integers and floats. Note that NaN is normally encoded as null in JSON.

**Integer** As above.

**Magnitude** As above where the value is expected between zero and one.

**Boolean** Not a problem

**Tuple** JSON lists are cast to tuples.

**NumericTuple** As above.

**XYCoordinates** As above

**Callable** Not supported

**Action** Not supported

**Composite** Not supported but also rarely used.

**ObjectSelector** Supports any other supported type.

**Selector** Supports any other supported type.

**ClassSelector** First tricky case that isn't callable. Classes could be encoded as appropriately qualified strings (i.e module/class name).

**List** Supported directly in JSON.

**HookList** Not supported.

**Dict** Supported as JSON mapping.

**Array** Could be supported e.g using list of list format in numpy array constructor.

**DataFrame** Can be supported using appropriate literal constructor (e.g dict of lists).

**Series** As above

**Path** String with validation.

**Filename** String with validation.

**Foldername** String with validation.

**FileSelector** String with validation.

**ListSelector** Value is a list (i.e supported)

**MultiFileSelector** As above.

**Date** Second non-callable case that needs handling. Can simple pick the appropriate ISO format for encoding/parsing as a string.

**CalendarDate** As above

**Color** Hex RGB string

**Range** Same as numeric tuple

**DateRange** Tuple represented as list of appropriately encoded date string.

**CalendarDateRange** As above.

I think this shows that JSON can support most common cases as long as callables are avoided. Nested parameterized objects can also be supported by taking the necessary class/keywords encoding and nesting it (the leaves have to be supported literal types). Note that `Parameters` could be given their own methods to support serialization/deserialization.

I am also thinking about whether param could output a JSON scheme or at least inform the user whether a given parameterized class can 1) always be encoded/decoded to JSON safely given the input/output is from param (i.e all parameters are constrained to types JSON can handle) 2) sometimes be encoded/decoded but will fail if say a callable is set on a `param.Parameter` at runtime (e.g encode what it can but also issue a warning about parameters that could not be encoded) or 3) can never be encoded due to use of a `Callable` an `Action` or a `HookList` for instance.

I am also thinking about whether this could be extended to support positional arguments or hooks to e.g allow a JSON encoding of say `hv.Curve([1,2,3])`. That said, I don't think such a feature is needed for the REST use case of the case where you want to configure parameterized objects from a file.

**Comment by jlstevens** [comment]
> ... since numbergen objects are just Parameterized objects nested into a Parameter value

Good point. For simple numbergen's it might just work as long as they don't have more complex parameters, e.g hold numpy random state.

On a related note, maybe things like numbergen's could be also be supported using `script_repr`, assuming the object can be reconstituted with `eval`. This might be an escape hatch but it makes the lines between the normal JSON serialization approach and the eval approach a bit blurry...

**Comment by jbednar** [comment]
Sure; there could be a special object that means "eval this string", which seems fine for a configuration language, if not for JSON serialization (due to safety).

**Comment by tonyfast** [comment]
@jlstevens can this issue be closed on be repurposed it seems like #414 addressed some or most of the issues.

**Comment by jlstevens** [comment]
I think so. There is always more to do but I would say *literal* serialization/deserialization has been addressed for now. Supporting yaml might be nice to have eventually but right now it doesn't seem like a priority. Closing.
