### ISSUE TITLE
ClassSelector and Dynamic don't accept default as first arg

### ISSUE THREAD

**Issue by ceball** [holoviz/param#393]
Leftover from #91 (and see discussion in #292).

**Comment by maximlt** [comment]
The complete list is:
- ClassSelector (`class_` is first)
- Dynamic
- Composite (`attribs` is first), even though 
- Selector (`objects` is first)

Too late for 2.0 ? @jbednar

**Comment by maximlt** [comment]
There's a more informative discussion in https://github.com/holoviz/param/issues/730.
