### ISSUE TITLE
Cannot override dynamic name of Parameterized class

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/param#403]
#### My Pain

At my site awesome-panel.org I have a lot of Pages. Each of these are `param.Parameterized` classes.

I would like to be able to let the user select a Page from a dropdown. And in the dropdown he should see a nice name. The user will be selecting the class and not an instance since I have a lot of Pages and don't want him/ her to wait for instantiating them all.

So I try defining a simple HomePage as below

```python
import param

class HomePage(param.Parameterized):
    name = param.String("Home")

home_page = HomePage()

print(home_page.name)
```

But this gives 

```bash
HomePage00002
```

#### Workaround

I can do 

```python
import param

class HomePage(param.Parameterized):
    def __init__(self, **params):
        params["name"]="Home"
        super().__init__(**params)

home_page = HomePage()

print(home_page.name)
```

which gives

```bash
Home
```

But this requires many more lines of code and also as I use the code for beginners in Python and then `__init__` and `**` sometimes appear a bit scary.

#### Solution

- If there is a solution using 1-2 lines of code please provide or
- Consider this a bug and fix it

Thanks.

**Comment by jbednar** [comment]
The intended usage of the `name` parameter is to name the instance, not the class, and so the expectation is that a name would be provided on instantiation: `home_page = HomePage("Home")`.   But it does seem like it should be possible to override the name at the class level, so if naming the instance does not meet your needs, I think we should add support for that.
