### ISSUE TITLE
set_param not working as expected

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/param#415]
Param: 1.9.3
Panel 0.9.5

Posted here on request of @philippjfr based on https://discourse.holoviz.org/t/how-to-trigger-param-depends-only-once-when-updating-multiple-parameters/848

#### Description of expected behavior and the observed behavior

I would expect to be able to use `set_param` to set multiple parameters but only run depending functions once. At least thats how @philippjfr says it should be working.

That is not how it is working for me.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import param
import panel as pn
pn.extension()

class MultiParamApp(param.Parameterized):
    count = param.Integer(0)
    param1 = param.Integer(0)
    param2 = param.Integer(0)
    update_once = param.Action()
    update_once_hack = param.Action()
    reset = param.Action()

    view = param.Parameter()

    def __init__(self, **params):
        super().__init__(**params)

        self._updating = False

        self.update_once = self._update_once
        self.update_once_hack = self._update_once_hack
        self.reset = self._reset

        self.view = pn.Param(
            self,
            widgets={
                "update_once": {"button_type": "danger"},
                "update_once_hack": {"button_type": "success"},
            },
        )

    @param.depends("param1", "param2", watch=True)
    def _inc(self):
        if not self._updating:
            self.count += 1

    def _update_once(self, _=None):
        self.param.set_param(param1=self.param1 + 1, param2=self.param2 + 1)

    def _update_once_hack(self, _=None):
        self._updating = True
        self._update_once()
        self._updating = False
        self._inc()

    def _reset(self, _=None):
        self._updating = True
        self.param1 = 0
        self.param2 = 0
        self.count = 0
        self._updating = False


MultiParamApp().view.servable()

```

#### Screenshots or screencasts of the bug in action

If I click the `Update Once` button I run the `_update_once` function but the `_inc` function is triggered twice. I would have wanted/ expected it to be triggered once.

![image](https://user-images.githubusercontent.com/42288570/85099079-bbde3b80-b1fc-11ea-9c38-34a665231681.png)

If I then click the `Update Once hack` button I get the expected behaviour.

![image](https://user-images.githubusercontent.com/42288570/85099110-ce587500-b1fc-11ea-91ae-655f8b895885.png)

**Comment by philippjfr** [comment]
Actually I wonder if https://github.com/holoviz/param/commit/da7a6eed63cbc9c9079dff41d8f831e2b43162c3 fixed this already.

**Comment by philippjfr** [comment]
Just tested, not fixed yet.
