### ISSUE TITLE
docstrings ordered by definition in class

### ISSUE THREAD

**Issue by ahuang11** [holoviz/param#443]
"Good question! Param was written for Python2, where the parameter order wasn’t preserved usefully, so we sorted them in various places. For Panel we now respect the definition order, and I think the Param docstring should do that now as well. I’m not sure whether this should be configurable or simply stop sorting altogether. My guess is that we don’t need a configuration option to control it, as we’ve never defined what the docstring behavior is, but maybe someone will complain if we don’t allow the old behavior to be restored. In any case I think it’s as simple as removing "sorted()` in ParamPager.param_docstrings, though there may be some other sorting elsewhere. Indeed, probably most “.sort()” and “sorted()” calls should be removed everywhere in the Param source code, because most are probably destroying user-created ordering. I’d appreciate seeing an issue on Param proposing removing such sorting, and/or a PR removing it specifically for the docstrings."

From jbednar
https://discourse.holoviz.org/t/is-there-a-way-to-make-docstring-follow-the-order-that-params-are-specified/1336/4

Or maybe sort based on setting the precedence value as slamer59 mentioned on the discourse.

**Comment by jbednar** [comment]
I'd vote for both, which I think is what panel does; use definition order for the same precedence, but globally sort by precedence as well.

**Comment by jbednar** [comment]
Fixed in #445
