### ISSUE TITLE
Param Reference Guide "Click Expansion" not working - I.E. GUIDE NOT USEFULL!

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/param#447]
In order to help a user in the discourse forum I had to check the param documentation.

https://param.holoviz.org/Reference_Manual/param.html

But I can see the expansion when you click the "+" no longer works. I.e. now you there is really no param documentation available if you are interested.

![param_expansion_not_working](https://user-images.githubusercontent.com/42288570/102167969-b56d0b80-3e8f-11eb-884a-cfdde3b14e92.gif)

**Comment by ceball** [comment]
This might be fixed by a new doc build: https://github.com/pyviz-dev/nbsite/pull/172

**Comment by jbednar** [comment]
Seems to be fixed in https://pyviz-dev.github.io/param/reference.html, though there are no longer any + signs at all, so maybe it's only fixed by default, but I'll take it!
