### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/param#452]
When looking at https://param.holoviz.org/Reference_Manual/param.html it shows the following:

![image](https://user-images.githubusercontent.com/19758978/106275145-ab338080-6235-11eb-96ad-034e6588face.png)

**Comment by philippjfr** [comment]
Thanks, looks like graphviz wasn't installed at build time. I'll try to finish off the website overhaul soon.

**Comment by grelston** [comment]
The [+] buttons are not expanding to reveal the class docs. Is this also caused by graphviz not being installed at build time?

**Comment by jlstevens** [comment]
> Is this also caused by graphviz not being installed at build time?

Unlikely. I think that is a separate issue. Thanks for reporting it!

**Comment by grelston** [comment]
No problem. I've opened a separate issue #453.
