### ISSUE TITLE
Add step to param.Range

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/param#466]
It could be nice if `param.Range` has a `step` argument like `param.Number`.  This would make it possible for me to do this:
``` python
import param 
import panel as pn

class Test(param.Parameterized):
    a = param.Range(default=(2, 5), bounds=(0, 10), step=0.2)  #  <-- I want to be able to do this
    b = param.Number(default=2, bounds=(0, 10), step=0.2)
    
pn.panel(Test())
```

Where right now, I need to do something like this to get the same effect:

``` python
class Test(param.Parameterized):
    a = param.Range(default=(2, 5), bounds=(0, 10))
    b = param.Number(default=2, bounds=(0, 10), step=0.2)
    
    def __init__(self, **params):
        super().__init__(**params)
        self.widgets = pn.Param(self, widgets={"a": {"step": 0.2}})
    
pn.panel(Test().widgets)
```

**Comment by jbednar** [comment]
Sounds like a good idea to me!

**Comment by Hoxbro** [comment]
Awesome! 

I just took a quick dab at it and got it to work first try, which begs the question: If it really can be so easy...
<img src="https://user-images.githubusercontent.com/19758978/117052334-e69f8880-ad17-11eb-95b1-7b52c22de882.png" width="70%" height="70%">

Used the code in my first post:
![limit](https://user-images.githubusercontent.com/19758978/117052914-98d75000-ad18-11eb-8758-e5b352c9b16d.gif)

**Comment by jbednar** [comment]
Great! PR?
