### ISSUE TITLE
CalendarDate accepts datetime.datetime values

### ISSUE THREAD

**Issue by maximlt** [holoviz/param#489]
This snippet works without any error:

```python
import datetime

from param import Parameterized, CalendarDate

class A(Parameterized):
    cd = CalendarDate(datetime.datetime.now())
```

I expected this Parameter type to accept dates (e.g. `datetime.date.today()`) only. If this is a bug, it may be caused by the fact that `datetime.datetime` objects inherit from `datetime.date` (see this [SO answer](https://stackoverflow.com/a/23298608/10875966)).

**Comment by maximlt** [comment]
This is actually a known fact: https://github.com/holoviz/param/pull/348#issuecomment-517037116

**Comment by jbednar** [comment]
It's known, but not necessarily desirable.  Given how long CalendarDate has accepted datetimes, it may not be practical to change that now, but maybe there could be a flag `date_only` to enforce that it is strictly a date and not a datetime.

**Comment by maximlt** [comment]
Trying to see how `CalendarDate` is used out there:

* A [GH search returns](https://github.com/search?l=Python&p=2&q=%22import+param%22+CalendarDate&type=Code) just a few hits
* panel uses it to define parameters (e.g. value) of the DatePicker widget. Construction this widget with a `datetime.datetime` parameter raises an error down in Bokeh: `ValueError: failed to validate DatePicker(id='1060', ...).value: Expected a date value, got a datetime.datetime`. So making the change directly would apparently not affect panel and its users.

**Comment by jbednar** [comment]
Fine by me! Unless anyone else objects, I'm happy to start enforcing accepting dates only.
