### ISSUE TITLE
`param.List` doesn't respect `bounds` and `class_`

### ISSUE THREAD

**Issue by maximlt** [holoviz/param#491]
This snippet works fine while it should raise errors (for l1, l2 and l3):
```python
import param

class A(param.Parameterized):
    l1= param.List([0, 1], bounds=(2, 4))
    l2 = param.List([0], bounds=(2, 4))
    l3 = param.List(["a"], class_=str)

a = A()
a.l1 = [0]
a.l3 = [1]
```

This is because `List._validate_bounds()` and `List._validate_item_type` are never called.

(Which attribute between `class_` or `item_type` should be used?)

**Comment by jbednar** [comment]
Thanks! I just found the very same issue. I believe `item_type` is the better one, but there should have been a comment in there explaining why. @jlstevens, can you verify that?

**Comment by maximlt** [comment]
What a coincidence indeed! Note that bound and type checking both work fine in the current release, this bug is only present on master.

**Comment by jbednar** [comment]
Whew! Glad we caught it before release, then.

**Comment by philippjfr** [comment]
Thanks for catching this!
