### ISSUE TITLE
WARNING:param.main: pandas could not register all extension types imports failed with the following error: cannot import name 'ABCIndexClass

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/param#510]
Too new of pandas? Or Param?

**Comment by andhuang-CLGX** [comment]
pandas==1.3.0

**Comment by andhuang-CLGX** [comment]
Downgraded to 1.2.5 and works

**Comment by jbednar** [comment]
HoloViews has an issue like this (https://github.com/holoviz/holoviews/issues/5009), but the only thing param imports from pandas are DataFrame and Series, so param itself seems very unlikely to be sensitive to this API change in Pandas. Closing, but please do reopen if this issue can somehow be reproduced with Param alone.
