### ISSUE TITLE
Should changing a Parameter's name be an error?

### ISSUE THREAD

**Issue by jbednar** [holoviz/param#535]
At present, it is possible to change the internal name of a Parameter on an instance:

![image](https://user-images.githubusercontent.com/1695496/134710057-d60ea316-4efb-4b73-98c6-f90b274ea6f2.png)

Doing that seems like a bad idea, because of how the name is used interchangeably with the attribute name in the dictionary; if those two get out of sync, I'd expect bad things to happen. 

Unfortunately, the `name` is not simply a String Parameter, as it is needed within the definition of Parameter itself, and so it's not as simple as marking `name` constant.  I'm not sure if there's an easy way to make the name read only...

**Comment by philippjfr** [comment]
Shouldn't be hard to do, setattr on Parameter just needs to raise an error.
