### ISSUE TITLE
FileSelector/MultiFileSelector don't update objects when path is updated and FileSelector doesn't set its value

### ISSUE THREAD

**Issue by maximlt** [holoviz/param#545]
`FileSelector` behaves like `Selector` and should as such set its value to the first item of *objects*, *objects* being the result of a glob on *path*. When *path* is updated it should also update *objects*.

`MultiFileSelector` should also update *objects* when *path* is updated. Also the docs currently state that the default value is all of the matched files, but in practice it's None.

> A param.MultiFileSelector is the analog of ListSelector but for files, i.e., again supporting a path glob but allowing the user to select a list of filenames rather than a single filename. The default value in this case is all of the matched files, not just the first one.

```python
import param

class A(param.Parameterized):
    fs = param.FileSelector(path='/usr/share/*')
    mfs = param.MultiFileSelector(path='/usr/share/*')

a = A()

print(a.fs is None)  # True!
paths = a.param.fs.objects.copy()
a.param.fs.path = '/usr/bin/*'
print(a.param.fs.objects == paths)  # True!

print(a.mfs == a.param.mfs.default == None)  # True!
paths = a.param.mfs.objects.copy()
a.param.mfs.path = '/usr/bin/*'
print(a.param.mfs.objects == paths)  # True!
```

**Comment by maximlt** [comment]
Not updating *objects* when *path* changes seems like a bug to me.

But changing the default value of FileSelector (inconsistent with Selector) and MultiFileSelector (inconsistent with Selector but consistent with ListSelector) is a backwards incompatible change, which I'm less inclined to fix now.

**Comment by jbednar** [comment]
I vote for changing the default as indicated and for updating for path changes.  The default behavior of None is both inconsistent with the docs and also seems very unlikely to be useful in practice, and Param 2.0 is probably our only real chance to change that.  Updating for path changes is already covered by #546.
