### ISSUE TITLE
Allow init

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/param#595]
I'm trying to create auto generated typehints/ stubs for Parameterized classes.

A part of this is autogenerating the signature of `__init__` method.  Lets use the `Pipeline` of `Panel as an example`.

A simplified version of this is defined as

```python
class Pipeline(param.Parameter);

    show_header = param.Boolean(default=True)
    next = param.Action(default=lambda x: x.param.trigger('next'))
```

A simplified stub for this would look like

```python
class Pipeline(param.Parameter);

    show_header: bool=True
    next: Callable=...

    def(show_header: bool=True, next: Callable=...):
```

The problem here is that we probably don't want `next` included in `__init__`. But with `param` we have no way to indicate and know this.

## Solution

Add an argument `allow_init`. Its `True` by default on any parameter. But if you set it to `False` and its provided to `__init__` it should raise an error.

## Additional Context

`constant` serves a purpose which is close to `allow_init`. But you can set a `constant` parameter in the `__init__`.

**Comment by MarcSkovMadsen** [comment]
Ahhh `readonly` is what I have been looking for. 

I've never really understood readonly and I gave up on it some time ago. Should look at it again.

**Comment by jbednar** [comment]
Right; readonly is like constant, but can't be changed on an instance even in the constructor.
