### ISSUE TITLE
MultiFileSelector: path argument is not taken into account in default constructor

### ISSUE THREAD

**Issue by Trophime** [holoviz/param#607]
I'm trying to use MultiFileSelector as presented in panel 0.12.6 doc on Debian/Testing with python 3.9

#### Description of expected behavior and the observed behavior

```python
multiple_files          = param.MultiFileSelector(path='../../*/*.py?', precedence=0.5)
```

I expect the multifile selector to list only the requested files. In fact it only displays file in os.getcwd()

Looking at the `__init__.py` code for MultiFileSelector we can see that path argument is not used in the default constructor...

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import param
class MRecordData(param.Parameterized):
    fvariable  = param.MultiFileSelector(path='./data')
```

**Comment by jbednar** [comment]
As far as I can tell, Param is working as designed here:

```python
import param
class F(param.Parameterized):
    fs = param.MultiFileSelector(path='/usr/share/*')
    
f = F()
f.fs
```

<img width="1013" alt="image" src="https://github.com/holoviz/param/assets/1695496/e642054d-71cd-4acd-9e6b-4de3cbd5a1df">

I.e., it's checking that the default or subsequently defined values are included in the list of files specified by `path`. Is this maybe a bug report for Panel, indicating that Panel isn't giving the expected options? Feel free to re-open this if I've misunderstood what the bug report is meant to be.
