### ISSUE TITLE
Depends is sensitive to widget name

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/param#614]
#### ALL software version info
``` 
panel    0.13.0a46.post46+g255f41c9
param    1.12.1a1.post13+ga11767e
```

#### Description of expected behavior and the observed behavior
I have the following minimal example, which contains a function for loading data and then plotting data based on the `picker` widget.

I have added  `date_picker` in my example, which does nothing in the MRE but is used in my actual code. By having this widget with this name, the plot function is only called once, and then it becomes stale. 

https://user-images.githubusercontent.com/19758978/161953202-5f9fa236-c3be-47a0-8e91-2599394a02a8.mp4

If I remove the widget from `depends`, everything works as expected. But even more strange is it also works if I rename the widget from `date_widget` to another name like `adate_widget`.

https://user-images.githubusercontent.com/19758978/161953591-bd9c5f2b-8a81-4f21-a012-131b68b8d6c6.mp4

#### Complete, minimal, self-contained example code that reproduces the issue

``` python
import panel as pn
import param


class Example(param.Parameterized):
    da = param.Number(default=1)

    def __init__(self, **params):
        # Not used in this MRE
        self.date_picker = pn.widgets.MultiSelect(
            options=list("ABCD"),
        )
        self.picker = pn.widgets.MultiSelect(
            options=list("ABCD"),
        )
        super().__init__(**params)

    @param.depends(
        "date_picker.value",  
        "picker.value",
        watch=True,
    )
    def load_data(self):
        self.da += 1  # To trigger plot_time

    @param.depends("da")
    def plot_time(self):
        return self.picker.value

    def __panel__(self):
        return pn.Row(self.picker, self.plot_time)


pn.panel(Example().__panel__).servable()


```

**Comment by Hoxbro** [comment]
It also works if I rename `da` to `ada`.

**Comment by jbednar** [comment]
I'm not sure I follow what this code is meant to do. `param.depends` is meant for depending on a Parameter, while a widget is a Parameterized, not a Parameter. A Parameterized _has_ Parameters, but it is not itself a Parameter. I suspect it still works because the dotted notation eventually reaches a parameter, but I'm not surprised there are issues. 

The code I'd use for this situation would be:

```python
import param, panel as pn

class Example(param.Parameterized):
    da   = param.Number(default=1)
    date = param.ListSelector(default=["A"], objects=list("ABCD"))
    pick = param.ListSelector(default=["A"], objects=list("ABCD"))
    
    @param.depends("date", "pick", watch=True)
    def load_data(self):
        self.da += 1  # To trigger plot_time

    @param.depends("da")
    def plot_time(self):
        return self.pick

    def __panel__(self):
        return pn.Row(self.param.pick, self.plot_time)

pn.panel(Example().__panel__).servable()
```
which seems to work fine:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/1695496/162076133-b3559545-7933-4801-8283-1c135bcfc5e0.png">

Or, more simply (since I'm not sure what `da` or `load_data` achieve here):

```python
import param, panel as pn

class Example(param.Parameterized):
    date = param.ListSelector(default=["A"], objects=list("ABCD"))
    pick = param.ListSelector(default=["A"], objects=list("ABCD"))
    
    @param.depends("date", "pick")
    def plot_time(self):
        return self.pick

    def __panel__(self):
        return pn.Row(self.param.pick, self.plot_time)

pn.panel(Example().__panel__).servable()
```

**Comment by philippjfr** [comment]
>I suspect it still works because the dotted notation eventually reaches a parameter, but I'm not surprised there are issues.

Yeah, the problem is that it does work and lots of users are relying on this behavior. The same issue also occurs when you make `date_picker` and `picker`  parameters of the class at which point we do officially support it.

**Comment by Hoxbro** [comment]
> I'm not sure I follow what this code is meant to do.

I should have explained it in more detail, but the MRE is based on some code I wrote a couple of years ago. The code could, of course, be improved (a lot) by what I know now. I tried to test the old code with the newest version of panel and param, which gives this bug - the old versions of panel and params where the code works are 0.12.1 and 1.11.1, respectively.

**Comment by jbednar** [comment]
> Yeah, the problem is that it does work and lots of users are relying on this behavior. The same issue also occurs when you make date_picker and picker parameters of the class at which point we do officially support it.

Ah, ok. I guess you mean code like the following, which *is* supported:

```python
import param, panel as pn
pn.extension()

opts = list("ABCD")
class Example(param.Parameterized):
    da = param.Number(default=1)
    date_picker = param.Parameter(pn.widgets.MultiSelect(options=opts))
    picker = param.Parameter(pn.widgets.MultiSelect(options=opts))

    @param.depends(
        "date_picker.value",  
        "picker.value",
        watch=True,
    )
    def load_data(self):
        self.da += 1  # To trigger plot_time

    @param.depends("da")
    def plot_time(self):
        return self.picker.value

    def __panel__(self):
        return pn.Row(self.picker, self.plot_time)

pn.panel(Example().__panel__).servable()
```

In that case, looks like it's matching by substring "da" and hitting either "da" or "date_picker". That sounds fixable.
