### ISSUE TITLE
Make Param compatible with Python 2.7 again

### ISSUE THREAD

**Issue by maximlt** [holoviz/param#623]
Support for Python 2 should be dropped for the release of Param 2.0. however due to some unfortunate circumstances (CI not actually running on Python 2 and changes not compatible with Python 2 :( ) Param 1.12.1 was released while being incompatible with Python 2. From what I've seen, this is due to the use of `yield from` first introduced in https://github.com/holoviz/param/pull/591.

cc @philippjfr

**Comment by philippjfr** [comment]
Fixed https://github.com/holoviz/param/pull/624
