### ISSUE TITLE
Mapping ObjectSelector to multi choice panel widget produces error making selection or setting default

### ISSUE THREAD

**Issue by vlvalenti** [holoviz/param#650]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
panel 0.12.4 
param 1.12.0

#### Description of expected behavior and the observed behavior
When mapping a param ObjectSelector to a Panel multi choice widget, making a selection in the resulting widget or setting a default at the ObjectSelector creation produces an error. Param mistakenly returns that the selected or defaulted values are not in the available options, even when they are clearly seen in the error message to be available options. Even if I don't set a default value, making any selection leads to the same error. It does not matter if I use a list to set the available objects or if I use a dictionary (which is what I want to do), param still does not recognize the selected values as possible. This happens for both the MultiChoice and the MultiSelect widget, so I assume it is an issue with how param deals with multi selection and the ObjectSelector. 

Uncomment the default line to see the bug immediately, or make a selection in the widget to see it there. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
import param
import panel as pn
pn.extension()

class test(param.Parameterized):
    plot_type = param.ObjectSelector(
#         objects=['xyc', 'yzc'],
        objects={'XY Contours': 'xyc', 'YZ Contours': 'yzc'},
#         default=['xyc']
                                    )
    
    def __init__(self, **params):
        super().__init__(**params)
        self.row = pn.Row(pn.Param(self.param, parameters=['plot_type'], widgets={
            'plot_type': {'type': pn.widgets.MultiChoice}
        }))
        
    def update_options(self):
        self.param.plot_type.objects = {'Time series': 'ts'}
        


t = test()

t.row
```

#### Stack  traceback and/or browser JavaScript console output
<img width="1172" alt="Screen Shot 2022-08-19 at 4 28 34 PM" src="https://user-images.githubusercontent.com/71399442/185719112-707e955e-364b-4792-a2c9-3519e8908f56.png">

**Comment by jbednar** [comment]
It looks like you're setting the default to a _list_ containing one string `['xyc']`, while the allowed options are just strings, not lists. Plus an ObjectSelector, selecting one of the given items, won't be compatible with a MultiChoice widget, whose value is a list of items. Should work if you use a default of `'xyc'` and a `Select` widget rather than a MultiChoice widget. Also an unusual style of using Panel and Param together, but maybe there's a good reason for that.
