### ISSUE TITLE
depends resolves unbound parameter instance in unexpected ways

### ISSUE THREAD

**Issue by madeline-scyphers** [holoviz/param#656]
#### ALL software version info
Python 3.9.13
macos m1 - 12.4 (native python)
safari
panel 0.14.0
param 1.12.2

#### Description of expected behavior and the observed behavior

I like to use classes for a lot of my panel apps because it gives a self contained app and it gives an init for grabbing data from an external data source. It can be hard though to find mappings for all of the param parameters to panel widgets, and some don't have mappings, plus most of the docs for panel don't use param. So I have been playing around with trying to use pn.depends and pn.bind in classes but encountering some rough edges, which led me to using them in parameterized classes, which led me to this. If you use pn.depends on a panel widget inside a parameterized class, it fires the method twice, with some weird behavior.

#### Complete, minimal, self-contained example code that reproduces the issue

This is me changing the selector twice

```python
import param
import panel as pn


class Test(param.Parameterized):
    w = pn.widgets.Select(options=["a", "b", "c"])

    @pn.depends(w, watch=True)
    def print_(self):
        print("hello world")
        try:
            self.w
        except AttributeError:
            pass
        print("self: ", repr(self), end="\n\n")

t = Test()
pn.Row(t.w)
```

So if we change the selector then it prints "hello world" twice. But weirder, self is different each time. Here is the output
```bash
hello world
self: Test(name='Test08207')

hello world
self: 'c'

hello world
self: Test(name='Test08207')

hello world
self: 'b'
```

So the first time it is being handed self, but the second time it is being handed w.param.value. Also if we make it a staticmethod, then it only fires one, and it is only handed w.param.value.

#### Screenshots or screencasts of the bug in action

I used a button in this example for simplicity, but a selector above since the button only real param.Parameter internally is value, so using Selector and Button at least means it more than just boolean like ones.

This is me clicking the button twice

<img width="657" alt="image" src="https://user-images.githubusercontent.com/93053005/198412061-47e3cb12-a8a8-4475-9729-816522526c94.png">

**Comment by philippjfr** [comment]
Sorry, I completely misread your example. Declaring widgets as class-variables is **strongly** discouraged precisely because it can cause problems like this. You should either instantiate the widget in the constructor of the class or declare a Parameter which you then convert to a widget, i.e. either:

```python
class Test(param.Parameterized):
    w = param.Selector(objects=["a", "b", "c"])

    @pn.depends('w', watch=True)
    def print_(self):
        print("hello world")
        try:
            self.w
        except AttributeError:
            pass
        print("self: ", repr(self), end="\n\n")
```

or:


class Test(param.Parameterized):

    def __init__(self, **params):
        super().__init__(**params)
        self._w = pn.widgets.Select(options=["a", "b", "c"])
        self._w.param.watch(self._print, 'value')

    def print_(self, *events):
        print("hello world")
        try:
            self.w
        except AttributeError:
            pass
        print("self: ", repr(self), end="\n\n")
```

**Comment by madeline-scyphers** [comment]
@philippjfr That is fair enough and makes sense, I am assuming that param inside a parameterized class's __init__ is doing a similar thing as dataclass or attrs do in their __new__ to turn class variables into instance variables, but also param is then watching for events and other things like that. 

I just also wanted to mention that the documentation doesn't give that feeling. The impression I and another user have gotten is that most of the examples are around pn.bind, pn.depends, etc. and there isn't nearly as much about parameterized classes and neither of us found another about what happens when you can't figure out how to map a certain Parameter to the panel widget you actually want, which is what partially what led to this.

The differences between between those two different api styles feels like a bit of a deadend instead of a shortcut, https://holoviz.org/background.html#shortcuts-not-dead-ends, especially if you don't find the ways to do it. You start out with simpler apps using bind and pn.depends, then it gets larger and switch to a Parameterized class and those don't work any more, and you now need to figure out the which Parameters to use and class mappings between Parameters and widgets if you don't like the default. The second option you specified would potentially be good as well for people looking for self contained apps not relying on global variables, but I didn't see any examples or anything like that anywhere.

One final thought, would it be possible to write in panel (since param doesn't have external dependencies at all, let alone to panel) a pn.ParamWidget that could be used on a class level on widgets to convert them to Parameters (inside Parameterized classes), kind of like param.ClassSelector, but probably only listening to value since I assume a bunch of other things might get changed internally. I don't know if this is possible, but it would stream line things for people and making the transition between one api style to the other a lot easier. If you think this is possible, you could try and point me in the right direction and I can try and see if I can get a start on it.

**Comment by philippjfr** [comment]
Thanks for your thoughtful comments! Unfortunately I'm about to log off and go on vacation so I can't reply in detail.

>One final thought, would it be possible to write in panel (since param doesn't have external dependencies at all, let alone to panel) a pn.ParamWidget that could be used on a class level on widgets to convert them to Parameters (inside Parameterized classes), kind of like param.ClassSelector, but probably only listening to value since I assume a bunch of other things might get changed internally.

So turns out you can already do this:

```python
class Test(param.Parameterized):
    
    widget = param.ClassSelector(
        class_=pn.widgets.Widget, default=pn.widgets.Select(options=['a', 'b'])
    )
    
    @param.depends('widget.value', watch=True)
    def print_(self):
        print(self.widget.value)
```

Give it a try and see if this is enough for you needs. Wrapping this up in a pn.PanelWidget parameter might still be useful though.

**Comment by madeline-scyphers** [comment]
Great! Thanks, that is helpful. I think wrapping this up in a pn.ParamWidget or something might be nice. So you could could do something like

```python
class Test(param.Parameterized):
    
    widget = param.ParamWidget(pn.widgets.Select(options=['a', 'b']))
    
    @param.depends('widget.value', watch=True)
    def print_(self):
        print(self.widget.value)
```

Though, I don't know if it could streamline all of the .values. But if so, maybe it could be as simple as

```python
class Test(param.Parameterized):
    
    widget = param.ParamWidget(pn.widgets.Select(options=['a', 'b']))
    
    @param.depends('widget', watch=True)
    def print_(self):
        print(self.widget)
```

Anyways, enjoy your vacation! I can tinker with this a bit in my spare time when I am not working on my research.
