### ISSUE TITLE
param.Range does not check if values are numbers

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/param#660]
Param doesn't complain when the bounds of a `Range` Parameter are set with weird values.

```python
import param

class X(param.Parameterized):
    xlim = param.Range(bounds=('a', 'b'))

x = X()
```

This is because `_valudate_bounds` are not checking if the values are numbers, e.g., this is a valid comparison `"a" < "b"`.

https://github.com/holoviz/param/blob/ddcd5f36bcff1712f2c7fb984268a0ad6dc9649f/param/__init__.py#L2086-L2096

**Comment by jbednar** [comment]
I can replicate this behavior, and also consider it an error that we should catch.

**Comment by jbednar** [comment]
I think the code to fix this would be something like

```python
     def _validate_bounds(self, val, bounds, inclusive_bounds):
-        if bounds is None or (val is None and self.allow_None):
-            return
+        if bounds is None:
+            return
+
+        for b in bounds:
+            if b is not None and not _is_number(b):
+                raise ValueError(f"Range bound '{b}' can only be None or a "
+                                 f"numeric value, not type '{type(b).__name__}'.")
+
+        if val is None and self.allow_None:
+            return
+
```

but there will be merge conflicts if #808 is merged first, so we can come back to it after merging that.

**Comment by maximlt** [comment]
Yep it will look like something like that. You'll probably want to make sure that it's a change valid for the `DateRange` and `CalendarDateRange` subclasses.
