### ISSUE TITLE
param.String value validation based on a set of possible string values.

### ISSUE THREAD

**Issue by Amuoeba** [holoviz/param#686]
Validating of` param.String` is currently only possible via regular expressions. In cases where you have a specific list of possible string values this approach might become cumbersome especially if the list is really long. I propose we add another validation step for which the user can provide an optional `set()` of all possible values for that parameter. This type validation could be easily generalised to other `param` types.

I can work on this myself if I get approval from someone that is more closely related to the project.

**Comment by maximlt** [comment]
Cannot you use a `Selector` instead?

```python
class P(param.Parameterized):
    s = param.Selector(objects=long_list_of_strings)
```

**Comment by maximlt** [comment]
It seems to me the `Selector` approach meets the need of the OP. Please don't hesitate to chime in after I close the issue if you disagree! :)
