### ISSUE TITLE
Default value not in `.objects` when `check_on_set=False`

### ISSUE THREAD

**Issue by maximlt** [holoviz/param#693]
The [docs on Selectors](https://param.holoviz.org/user_guide/Parameter_Types.html?highlight=check_on_set#selectors) say:

> If the list of available objects is not meant be exhaustive, you can specify `check_on_set=False` (which automatically applies if the initial list is empty). Objects will then be added to the objects list whenever they are set, **including as the initial default.**

However it's not quite true, I think, as I'd expect `p.param.s.objects` to contain the default value?

```python
import param

class P(param.Parameterized):
    s = param.Selector(default=3, objects=[1, 2], check_on_set=False)

p = P()

print(p.s, p.param.s.objects)
# 3 [1, 2]
```

**Comment by jbednar** [comment]
Good catch; I think 3 should be put into the objects list in the above case.
