### ISSUE TITLE
Validation error messages refer to the super classes

### ISSUE THREAD

**Issue by maximlt** [holoviz/param#696]
Validation code in a Parameter often calls the Parameter's parents validation methods. The Parameter name is hard-coded in the validation error message, which means that users may receive an error message that is a bit confusing as it doesn't mention the type of the invalid Parameter but the type of one of its parents.

This snippet emits `ValueError: Tuple parameter 'r' only takes a tuple value, not <class 'str'>.` while the Parameter is a `Range`. `Range` is indeed a subclass of `Tuple`.

```python
import param

class P(param.Parameterized):
    r = param.Range()

P(r='test')
```

Substituting the hard-coded Parameter name with `self.__class__.__name__` would probably fix that.

**Comment by shobhitgupta01** [comment]
Hi
Can I work on this issue

**Comment by maximlt** [comment]
Actually fixed in https://github.com/holoviz/param/pull/808 🎉
