### ISSUE TITLE
Document Param 2.0 breaking changes

### ISSUE THREAD

**Issue by maximlt** [holoviz/param#727]
Listing the breaking changes made in Param 2.0 to list them in the release notes:
- https://github.com/holoviz/param/pull/726
- https://github.com/holoviz/param/pull/729
- https://github.com/holoviz/param/pull/605
- https://github.com/holoviz/param/pull/744
- https://github.com/holoviz/param/pull/767
- https://github.com/holoviz/param/pull/797
- https://github.com/holoviz/param/pull/796
- and more that I missed for sure

**Comment by philippjfr** [comment]
Not a breaking change but an announcement of a future breaking change:

- Param will enable `allow_refs` in future so any objects that are references, e.g. functions, parameters, reactive expressions and in the case of Panel widgets, will automatically resolve to their value when passed to a parameter. To disable this users will have to set `allow_refs=False` explicitly.
