### ISSUE TITLE
Add support for unicode (with python 2)?

### ISSUE THREAD

**Issue by ceball** [holoviz/param#73]

**Comment by jlstevens** [comment]
This is fairly important and quite an annoyance. I promise our HoloViews users that it will be fixed in the next release. See the last entry of the HoloViews FAQ: ioam/holoviews@d2dec608e

I'm sure we will have enough improvements by then to justify an updated release of param. :-)

**Comment by vascotenner** [comment]
I normally do something like:
```python
from __future__ import unicode_literals
import numpy as np
import holoviews as hv
```
But then params does not work anymore.

Related: https://github.com/ioam/holoviews/issues/29

**Comment by jlstevens** [comment]
I agree this is an important issue. Will we have a new param bug-fix release before param 2.0 where we can have this fixed?

**Comment by jbednar** [comment]
Let's discuss param releasing around 14 April; I'm waiting to hear some things about param from Chris.

**Comment by ablythed** [comment]
Closing. Works in Python 3 and Python 2 is no longer a priority.
