### ISSUE TITLE
Easier subclassing of Parameter

### ISSUE THREAD

**Issue by JonathanMair** [holoviz/param#748]
Hello! Many thanks for param, I'm new to it and I'm loving it. 

I have an application that I'm experimenting with migrating by adding Parameters to the key classes. I've run into something that I'm trying to do that doesn't work, and I'd be interested to understand why it doesn't—perhaps there's a good reason—and also to suggest that a fix might be considered. 

Let's say I have a class with the following signature before parameterizing:

```

class Pizza:

    def __init__(self, diameter: float, thickness: float, description: str, topping: Topping, style: PizzaStyle, ):
        pass

```

`diameter` and `thickness` are straightforward, but for the custom classes one needs to subclass Parameter. This is working fine for me, following the instructions in the documentation here: 

https://param.holoviz.org/user_guide/Parameters.html#specialized-parameter-types

For example: 

```

class PizzaStyle:
"""Class with attributes and methods, could be an enum"""

class PizzaStyleParam(Parameter):     
"""PizzaStyle Parameter value must be PizzaStyle object"""

    def _validate_value(self, val, allow_None):
        super(MortgageParameter, self)._validate_value(val, allow_None)
        if not isinstance(val, PizzaStyle):
            raise ValueError("type of PizzaStyle parameter %r must be a PizzaStyle, "
                             "not %r." % (self.name, val))

```
 
Then Pizza can be parameterised like this: 

```

class Pizza(Parameterized):
    diameter = param.Number(12, bounds=(6, 18), doc="pizza diameter in inches")
    pizzaStyle = PizzaStyleParam(default=PizzaStyle(**some_kw), doc="PizzaStyle object representing style of pizza")
    …

```  

This allows Pizza to be fully parameterised and I can benefit from the documentation feature of the param. Of course, the validation is really delegated to PizzaStyle class, which may or may not be parameterised, the only validation that the PizzaStyleParam does is to type check to make sure a PizzaStyle is supplied.

So far so good. However, in my real application, I have many custom classes that are properties of a few facing classes.  Since the custom Parameter subclass above is very simple, rather than writing one for each of my classes, I would like to write a standard Parameter subclass that will take a type at the level of the Parameterized class and will validate by checking that any parameter values correspond to that type. 

I have tried doing that in various ways something like this: 

```

class TypedParameter(Parameter):
    """Subclass of param.Parameter to allow for easy use of custom objects in Parameters"""

    def __init__(self, object_class, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.object_class = object_class

    def _validate_value(self, val, allow_None):
        super(MortgageParameter, self)._validate_value(val, allow_None)
        if not isinstance(val, self.object_class):
            raise ValueError("TypedParameter value %r must be an instance of the type supplied"
                             "not %r." % (self.name, val))

class Pizza(Parameterized):
    diameter = param.Number(12, bounds=(6, 18), doc="pizza diameter in inches")
    pizzaStyle = TypedParamter(
        object_class=PizzaStyle, 
        default=PizzaStyle(**some_kw),  
        doc="PizzaStyle object representing style of pizza"
        )
   toppings = TypedParamter(
        object_class=Topping, 
        default=PizzaStyle(**some_kw),  
        doc="PizzaStyle object representing style of pizza"
        )
    …

``` 

This doesn't work — I get ```AttributeError: 'TypedParameter' object has no attribute 'obj_class'``` . I have tried various workarounds, including trying to use __slots__ and nothing works for me. 

So briefly, my questions are: 

1. If I want to implement a TypedParameter subclass of Parameter along these lines, is there a way I can do it? Perhaps I'm just missing a simple way to pass arguments from the constructor.
2. Is there another way to achieve what I'm trying to do?
3. If the answer to 2 is 'no', could I suggest that a TypedParameter subclass could be added to param?

Many thanks

**Comment by JonathanMair** [comment]
Hi...a follow up...

OK, I think I've understood how this is supposed to be done: use a Selector or ListSelector and provide a list of possible classes or instances and set the value from them. 

This works to an extent but means that it means that there can't be type checking in the usual param way.

**Comment by Hoxbro** [comment]
I think what you are looking for is `param.ClassSelector`.

**Comment by JonathanMair** [comment]
Hi — yes indeed, many thanks! I should have read the docs better, I think I glossed over that thinking from the name it was the class that is actually called something like SelectorBase.

**Comment by jbednar** [comment]
@JonathanMair , assuming that ClassSelector met your needs here (as it sounds like it does), I'll close this issue, but if you see a good way to improve the docs so that other people will be able to have a smoother experience, please contribute a PR for the docs or else open an issue with text that we can make into a PR. Thanks!

**Comment by JonathanMair** [comment]
@jbednar thanks—yes I'll have a go at implementing the thing I've been working on so I have it clear in my head and then think about suggesting an improvement. Possibly just my fault for skimming though! Thanks again.
