### ISSUE TITLE
Pickle Serialization doesn't work for param.Parameterized with @param.depends function decorators

### ISSUE THREAD

**Issue by steenha** [holoviz/param#757]
VSCode, Jupyter Notebook Extension
params==1.13.0
python==3.11.3
OS=Ubuntu 22.04 (Windows Subsystem for Linux)

#### Description of expected behavior and the observed behavior
Normal param.Parameterized classes can be pickled just fine, but when adding the @param.depends function decorator to a method, the class can no longer be serialized with pickle

#### Complete, minimal, self-contained example code that reproduces the issue
```
import param
from param import Integer
import pickle

class package_nodepends(param.Parameterized):
    a = Integer(1)
    b = Integer(1)

class package_depends(param.Parameterized):
    a = Integer(1)
    b = Integer(1)
    c = Integer(1, doc="DERIVED: c=a+b")

    @param.depends("a", "b", watch=True, on_init=True) 
    def update_c(self): self.c = self.a+self.b

p_nodep = package_nodepends()
p_dep = package_depends()

with open("p_nodep.pkl", "wb") as pkl:
    pickle.dump(p_nodep, pkl)  # works fine

with open("p_dep.pkl", "wb") as pkl:
    pickle.dump(p_dep, pkl)  # fails here
```

#### Stack traceback and/or browser JavaScript console output
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 24
     21     pickle.dump(p_nodep, pkl)
     23 with open("p_dep.pkl", "wb") as pkl:
---> 24     pickle.dump(p_dep, pkl)

AttributeError: Can't pickle local object '_m_caller..caller'
```

**Comment by samimia-swks** [comment]
What is interesting is that the current implementation of the depends() decorator, shown below, does use functools.wrap from the standard library; and that is supposed to solve the problem of pickeling decorated functions per [this article](https://towardsdatascience.com/why-you-should-wrap-decorators-in-python-5ac3676835f9)... 

```python
@accept_arguments
def depends(func, *dependencies, watch=False, on_init=False, **kw):
    if iscoroutinefunction(func):
        @wraps(func)
        async def _depends(*args, **kw):
            return await func(*args, **kw)
    else:
        @wraps(func)
        def _depends(*args, **kw):
            return func(*args, **kw)
```

**Comment by maximlt** [comment]
Hi @steenha and @samimia-swks,

Param unfortunately doesn't have too many tests that exert serializing Param objects with `pickle`. I think it actually just has one!

https://github.com/holoviz/param/blob/154cdbe1015f9410b1cf417220697b1afd41f248/tests/testparameterizedobject.py#L383-L388

As it is it's not too surprising that pickling "more" complex objects fail :/ Contributions in this area are more than welcomed. It'd be for instance interesting to know whether pickling `package_depends` worked in the past, and if so what change (there were lots of changes in the internals of `param.depends`) broke it.
