### ISSUE TITLE
IPython parameter autocompletion breaks if parameter has empty docstring

### ISSUE THREAD

**Issue by philippjfr** [holoviz/param#78]
Simplest example:

``` python
class A(param.Parameterized):
    a = param.Boolean(default=False, doc="")   
```

**Comment by jlstevens** [comment]
Solution: don't have empty docstrings? :-)

**Comment by jbednar** [comment]
Solution: don't have empty docstrings? :-)

**Comment by philippjfr** [comment]
Agreed :) Still shouldn't break though. Simple fix but I'll leave it to Jean-Luc.

**Comment by jlstevens** [comment]
Ok sure! I'll have a look at this shortly...

 I think parameters shouldn't ever have empty docstrings but I also agree that a nicer warning should be generated should such an empty docstring be encountered.

**Comment by ceball** [comment]
Check if still a problem

**Comment by philippjfr** [comment]
Autocompletion now based on the signature so no longer has this issue.
