### ISSUE TITLE
param.pprint breaks if HoloViews is imported

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/param#785]
Running the following: 
``` python
import holoviews as hv
import param


class T(param.Parameterized):
    a = param.Number(1)


t = T()
t.param.pprint()
```

Will give the following traceback:
``` python-traceback
Traceback (most recent call last):
  File "/home/shh/Development/holoviz/development/tmp.py", line 10, in <module>
    t.param.pprint()
  File "/home/shh/Repos/holoviz/param/param/parameterized.py", line 2894, in pprint
    return partial(self_._pprint, self, imports=imports, prefix=prefix,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/Repos/holoviz/param/param/_utils.py", line 105, in wrapper
    result = user_function(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/Repos/holoviz/param/param/parameterized.py", line 2914, in _pprint
    args = spec.args[1:] if spec.args[0] == 'self' else spec.args
                            ~~~~~~~~~^^^
IndexError: list index out of range
```

If I add `__init__` to the class, it works or remove the holoviews import it works again.

``` python
class T(param.Parameterized):
    a = param.Number(1)
    
    def __init__(self):
        super().__init__()
```

**Comment by maximlt** [comment]
It can be reproduced with:

```python
import inspect
import param


class A(param.Parameterized): pass

A.__init__.__signature__ = inspect.Signature([inspect.Parameter('test', inspect.Parameter.KEYWORD_ONLY)])


class T(param.Parameterized):
    a = param.Number(1)


t = T()
print(t.param.pprint())
```

This is indeed what HoloViews is doing:
https://github.com/holoviz/holoviews/blob/a64cfc544acc94b3806d427912047ca660253587/holoviews/util/__init__.py#L626

But I don't understand yet why updating the docstring of a class (`A`) affects another one (`T`).

**Comment by Hoxbro** [comment]
Isn't it because A's `__init__` is `param.parameterized.Parameterized.__init__`
![image](https://github.com/holoviz/param/assets/19758978/1068c8d1-af99-4c54-b17b-4289f572b8de)

**Comment by maximlt** [comment]
Yep indeed I also just figured this out. So I think there's two workaround?

- param could just check that `'self'` is in `spec.args`, that should be sufficient to avoid this breakage
- HoloViews could add an `__init__` method to its `output` ParameterizedFunction to avoid overriding the `__signature__` of all the Parameterized objects :)

The real issue to fix has been well defined in https://github.com/holoviz/param/issues/371.

**Comment by Hoxbro** [comment]
I heavily favor number two. I think it is "correct" that params raise an error, as there is something "wrong" with what HoloViews does.

**Comment by maximlt** [comment]
Ok I got slightly confused by `inspect.signature` that doesn't return the same output on the class or instance:
![image](https://github.com/holoviz/param/assets/35924738/fe8afdad-96f1-4d7c-8dd3-505a6d9c08dc)
