### ISSUE TITLE
Selector regression in an inheritance context?

### ISSUE THREAD

**Issue by maximlt** [holoviz/param#793]
There's maybe a regression on the _main_ branch brought by the sentinel PR, that happens when setting a Selector value on an instance of a subclass and that leads to the `objects` of the super class being updated.

Here's the most basic example:

```python
class A(param.Parameterized):
    p = param.Selector()

class B(A):
    p = param.Selector()


b = B()
b.p = 2

# Before [], now [2]
print(A.param.p.objects)
```

And maybe a more realistic example:
```python
import param

class A(param.Parameterized):
    p = param.Selector(objects=[1, 2], check_on_set=False)

class B(A):
    p = param.Selector(default=2)


b = B()
b.p = 3

# Before [1, 2], now [1, 2, 3]
print(A.param.p.objects)
```

That is probably again a problem of `objects` being a mutable object, this time being shared across a class and all of its subclasses and their instances. I come to wonder whether `objects` accepting a mutable object (list/dict) is actually a good idea, and if instead it wouldn't be best if it'd accept a factory function. cc @jbednar to gauge how blocking this is for the release of Param 2.0

**Comment by jbednar** [comment]
When instantiate=True leads to copying the Parameter object, can we make it do a copy (not a deepcopy) of any mutable slot values (or all slot values, which should have the same result)? That seems cheap enough and preserves object identity for the items in the Selector while avoiding this problem.

**Comment by maximlt** [comment]
> When instantiate=True leads to copying the Parameter object, can we make it do a copy (not a deepcopy) of any mutable slot values (or all slot values, which should have the same result)?

Yes there's nothing that prevents us from doing that when `instantiate=True`. However that doesn't resolve neither this issue nor https://github.com/holoviz/param/issues/746 as they deal with the `Selector` Parameter which is set by default with `instantiate=False`, right?

**Comment by jbednar** [comment]
I've corrected my message above to say `per_instance` where I had written `instantiate`; I always get those two confused. `per_instance` is the relevant one here, which controls instantiation of the Parameter object per instance, not instantiation of the default value into a current value (`instantiate=True`).
