### ISSUE TITLE
Simplify Number's _checkBounds() method

### ISSUE THREAD

**Issue by ceball** [holoviz/param#83]
Could consider simplifying the range check to something like this untested code:

``` python
          too_low = False if vmin is None else
                    (val < vmin if incmin else val <= vmin) and
                    (val > vmin if incmin else val <= vmin)

          too_high = ...

          if too_low or too_high:
              raise ValueError("Parameter '%s' must be in the range %s" %(self._attrib_name,self.rangestr()))
```

where `self.rangestr()` formats the range using the usual notation for indicating exclusivity, e.g. "[0,10)".

**Comment by jbednar** [comment]
I can't understand how that code would work.  Shouldn't it be:

``
too_low = False if vmin is None else (val < vmin if incmin else val <= vmin)
too_high = ...
``

though it might be clearer (with fewer double negatives) as:

``
allowed_low = (vmin is None) or (val > vmin if incmin else val >= vmin)
allowed_high = 
``

**Comment by ceball** [comment]
I just copied and pasted your comment from the code; glad to see your programming skills have improved over the years ;)

Also just a note that before making any simplification, it would be a good idea to have a proper test in param. I only saw a partial test (https://github.com/ioam/param/blob/master/tests/testparameterizedobject.py#L209), and it seems not even topographica's tests touch all of `_checkBounds()`: http://doozy.inf.ed.ac.uk/buildbot/coverage/external_param_param___init__.html#n616

**Comment by jbednar** [comment]
:-)

**Comment by jbednar** [comment]
Though I guess it could be easier to read as:

```python
too_low = (vmin is not None) and (val < vmin if incmin else val <= vmin)
too_high = ...
```

**Comment by philippjfr** [comment]
Personally I'm quite happy with the very explicit error messages rather than using one generic error message. Don't have a strong opinion though.

**Comment by jbednar** [comment]
I don't have a strong opinion either. Note that changing the message should be done for a good reason (e.g. that some error condition wasn't caught before), because it affects whether people can find relevant issues on StackOverflow by searching on error message text.

**Comment by ablythed** [comment]
Closing as this does not seem to be a priority anymore.
