### ISSUE TITLE
Redefined param in child Parameterized class inherits the 'bounds' of the parameter in the parent class

### ISSUE THREAD

**Issue by samimia-swks** [holoviz/param#837]
#### ALL software version info
v2.0.0a3

#### Description of expected behavior and the observed behavior
Say I have a child Parametrized class which inherits from a parent Parameterized class and redefines one of its parameters from a param.Integer to a param.List. If the param.Integer had a bounds defined, the param.List in the child class seems to inherit those bounds, which doesn't really make sense (the bounds of an integer enforce a range on the number, but the bounds of a list enforce a range on the length of the list). 

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import param


class parent(param.Parameterized):
    p = param.Integer(None, bounds=(1, None))


class child(parent):
    p = param.List([])


p = parent()
c = child()

```

The above code fails with `ValueError: List parameter 'child.p' length must be at least 1, not 0.`
I expect `p = param.List([])` to completely override `p = param.Integer(None, bounds=(1, None))`, and a default value of [] to be valid.

**Comment by samimia-swks** [comment]
I see. Thanks for the detailed explanation.

**Comment by maximlt** [comment]
We could improve the error message here. The error happens while creating the `child` class when it detects that the type of a Parameter has changed. In that case we could catch the validation error (a mix of `ValueError`, `TypeError` `OSError`) and enhance it with some more context.
