### ISSUE TITLE
param.A + param.B = Param.C, how to express this relationship beween parameters ?

### ISSUE THREAD

**Issue by hengaini2055** [holoviz/param#896]
#### Is your feature request related to a problem? Please describe.
A parameterized class instance will be a real object having so many parameters. These parameters have relationships, such as param. C = param. A + param.B

#### Describe the solution you'd like
Is there a attribute that express this relationship between parameters? And then execute this formulaes automatically or manually.

#### Describe alternatives you've considered
The atom param like A or B should have a ready or not attribute. The all relationships between all parameters like networks DAG can automatically update or calculate. 

#### Additional context
NO!

**Comment by MarcSkovMadsen** [comment]
I think Param.rx and Param.bind is What you are looking for https://param.holoviz.org/user_guide/Reactive_Expressions.html

**Comment by hengaini2055** [comment]
Thanks! I will read the doc.
