### ISSUE TITLE
Add .is_active parameter to reactive expressions

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/param#912]
I would like to start using reactive expressions as I start to realize they are a powerful extension of `pn.bind`. 

One pattern I would often like to do is to disable components and/ or add loading indicators while a reactive expression is evaluating.

## Context

I can do this manually by using another  `is_active` reactive expression.

```python
import panel as pn
from time import sleep
pn.extension()

is_active = pn.rx(False)

submit = pn.widgets.Button(name="Start the wind turbine", loading=is_active, disabled=is_active)

def run(clicked):
    is_active.rx.value = True
    sleep(0.5)
    print("done")
    is_active.rx.value = False

rx_run = pn.rx(run)(submit)

# Figure out how to watch

pn.Column(submit, rx_run).servable()
```

https://github.com/holoviz/param/assets/42288570/1754fd65-b1e3-471d-a26e-7759ee7515ab

Please note that this example also experiences the issue in https://github.com/holoviz/panel/issues/6426.

## Request

Please make this pattern really simple to use by adding an `.is_active` parameter to reactive expressions. Something like

```python
rx_run.rx.is_active
```

that I can *bind* to.

## Bonus question:

Instead of changing the value of a reactive expression two times as in the example. Is it possible to use a *context manager* similar to 

```python
with some_parameterized.param.update(value=False):
   ...
```

**Comment by philippjfr** [comment]
This already exists and has to be documented, specifically it's `rx_run.rx.updating()`

**Comment by MarcSkovMadsen** [comment]
How would I combine `updating()` with `.watch`. I can't figure out how as `.watch(...)` just returns None. I.e. I don't get a handle on anything I can do `.rx.updating()` on.

```python
import panel as pn

pn.extension()

# Declare state of application
is_stopped=pn.rx(True)

def name(stopped):
    if stopped:
        return "Start the wind turbine"
    else:
        return "Stop the wind turbine"

rx_name = pn.rx(name)(is_stopped)

submit = pn.widgets.Button(name=rx_name)

def start_stop_wind_turbine(clicked):
    print("running action")
    is_stopped.rx.value = not is_stopped.rx.value

run_rx = submit.rx.watch(start_stop_wind_turbine)

pn.Column(submit).servable()
```

**Comment by MarcSkovMadsen** [comment]
Add the same time I am think whether the `.rx` `.watch` api is what you would expect. Why do you have to specify a function as argument. Why can't you just watch and execute the pipeline as in

```python
import panel as pn
from time import sleep
pn.extension()

is_active = pn.rx(False)

submit = pn.widgets.Button(name="Start the wind turbine", loading=is_active, disabled=is_active)

def run(clicked):
    is_active.rx.value = True
    sleep(0.5)
    print("done")
    is_active.rx.value = False

rx_run = pn.rx(run)(submit).rx.watch()

# Figure out how to watch

pn.Column(submit).servable()
```

![image](https://github.com/holoviz/param/assets/42288570/9b0d8c85-f4f3-436a-9c98-cee53feb133d)
