### ISSUE TITLE
Parameter called outputs does not work with `.rx`

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/param#928]
``` python
import param


class T(param.Parameterized):
    outputs = param.Number(1)
    results = param.Number(1)


T().param.outputs.rx.not_()  # Does not work
T().param.results.rx.not_()  # Does work
```

Using outputs raises the following `AttributeError: 'function' object has no attribute 'rx'`. This is likely because of this method: https://github.com/holoviz/param/blob/dae8fc4a7b47079468ad5da0b486a779e963351b/param/parameterized.py#L2786

**Comment by maximlt** [comment]
I think you should instead use `__getitem__` and call `T().param["outputs"].rx.not_()`. I don't think it's a bug but more of a gotcha, it doesn't apply to `outputs` only but to every name in the `.param` namespace. IIRC, `obj.param.<parameter_name>` is just syntactic sugar for `obj.param[<parameter_name]`.

**Comment by philippjfr** [comment]
Didn't realize this is what you were referring too. This is indeed not a bug, much like in pandas you can access columns with getattr you can access parameters but if there's a clash you won't be able to and have to fall back to getitem.

**Comment by jbednar** [comment]
Probably should document and explain this somewhere?

**Comment by philippjfr** [comment]
Would be surprised if it wasn't but should double check.
