### ISSUE TITLE
Type checking broken using booleans

### ISSUE THREAD

**Issue by jlstevens** [holoviz/param#96]
I discovered that this class:

``` python
class A(param.Parameterized):
    a = param.Number(default=3)
    def __init__(self, a):
        super(A, self).__init__(a=a)
```

Behaves like this:

``` python
>>> A(5)    # Fine
>>> A('b')  # Complains appropriately
>>> A(True) # No error!
```

What is going on here?

**Comment by jbednar** [comment]
>>> isinstance(5, numbers.Number)
True
>>> isinstance('b', numbers.Number)
False
>>> isinstance(True, numbers.Number)
True

I.e., Boolean is considered a numeric type by Python.  We could check for Boolean types and explicitly exclude them, if you wish to make that change in param._is_number().

**Comment by ceball** [comment]
In python (at least in 2 from whenever it was bool appeared, don't know about 3) bool inherits from int, so it might surprise a python user to find a python boolean is not a number according to param. I think I  do prefer what Jean-Luc expected, i.e. for a python boolean to not be a number according to param, but not enough to make that change myself...

**Comment by jlstevens** [comment]
Apparently this behavior still holds in Python 3 - I just checked.

**Comment by ceball** [comment]
See also #82

**Comment by jbednar** [comment]
I think this behavior is well established for Python, i.e. that Booleans can transparently be used as numbers, and so it seems problematic to try to make a distinction now.
