### ISSUE TITLE
import param 2.1.1 tries to run git subprocess

### ISSUE THREAD

**Issue by cdeil** [holoviz/param#964]
#### ALL software version info

```
python=3.12
param = 2.1.1
```

System: macOS

#### Description of expected behavior and the observed behavior

Observed: Install Python and `pip install param` on a Mac that has no git installed, then `python -c 'import param` will try to run `git` and macOS will prompt the user if they want to install the MacOS command line developer tools.

Expected: `import param` should not try to run `git` for stable versions like `param=2.1.1` from PyPI.

It's confusing for Python/Panel newbies that haven't learned git and it's annoying for anyone that doesn't have git installed on some macOS box. It's not a bit deal however, I will simply install git for now or could run my Panel app (which triggered the param import) without git, i.e. this is just an annoying popup, not a blocker.

#### Screenshots or screencasts of the bug in action

The following screenshot shows a stacktrace where this occurs in the Panel version.py that ultimately leads to the `subprocess` call that tries to run git.

![F450EFF0-AB1E-40A4-8196-887DA8AE84DC](https://github.com/user-attachments/assets/58352c0f-8709-4845-9559-00d7f3c8671d)

**Comment by hoxbro** [comment]
I think this is coming from Panel, which used to run param.version. We have moved away from this in Panel 1.5. Can you try a panel dev release and see if it still happens?

**Comment by cdeil** [comment]
Oups, you're right.  All good with `panel 1.5.0b4`.
